### ISSUE TITLE
ERROR: Another instance of the 3DMigoto Loader is already running. Please close it and try again

### ISSUE THREAD

**Issue by Tysaki** [SilentNightSound/GI-Model-Importer#101]
"ERROR: Another instance of the 3DMigoto Loader is already running. Please close it and try again"

keeps happening alot after quitting the game and trying to launch again.
i cant find 3dm in taskmanager or cmd tasklist, so not sure whats going on there.

only workaround for now is launching the game vanilla and quiting and hoping it works afterwards or restarting pc, which both is kinda annoying.

i play the game with arg "-window-mode exclusive" if that helps. lmk if you need more info

**Comment by fantaststriker** [comment]
I had the same issue. What I did was pretty much saved a copy of my mods shader cache and shader fixes, then uninstalled everything. After I just installed and launched a new folder of 3DMigoto.

**Comment by starwaver** [comment]
I keep getting this error too, but it happens even if I haven't even opened the game.
Have yet to get it working even trying to run it first thing after starting computer

**Comment by EmmaCoded** [comment]
> I keep getting this error too, but it happens even if I haven't even opened the game. Have yet to get it working even trying to run it first thing after starting computer
> 
> Update: Got it working by changing the setting to 3dgimoto.dll, running it and failed, then changing it back to d3d11.dll

How you do it exactly?
