### ISSUE TITLE
Game not opening when 3dmigoto is running on a VM on mac

### ISSUE THREAD

**Issue by thinkerdevoe4** [SilentNightSound/GI-Model-Importer#102]
Game runs fine on the VM normally, but doesn't launch at all when 3dmigoto is running. 3dmigoto closes by itself after a short delay once game is launched (both launched as admin), but the game itself doesn't boot up. Task manager shows game isn't using any bit of the CPU at all when this happens, so game is straight up not running. Double and triple checked d3dx file, the file path to GenshinImpact.exe is listed correctly. Sometimes the game opens up to a white screen and then closes after a bit of a delay. Not sure how to fix this.

Edit: VM is Parallels 17 for M1 mac

**Comment by leotorrez** [comment]
There could be a mod crashing your game. try turning all mods and shaderfixes off to test

**Comment by op06072** [comment]
Same issue for me

**Comment by leotorrez** [comment]
I've come to learn that genshin has Virtual Machine protection. it is not related to 3dm

**Comment by op06072** [comment]
> I've come to learn that genshin has Virtual Machine protection. it is not related to 3dm

parallels can run just genshin.
