### ISSUE TITLE
Mods are unable to load...

### ISSUE THREAD

**Issue by tsumeru39** [SilentNightSound/GI-Model-Importer#104]
I got GIMI today, and after a while of having it, the mods stopped loading entirely. I have used the loader repeatedly with a closed and reloaded game, I have pressed F10, I have even redownloaded everything and cleared the Cache and Shader files. This started happening after getting 2 Honkai: Star Rail mods and trying to use them. If this info is helpful, all my mods were .zip files and from Gamebanana. The text in the corner for the mods working does not show up on startup (of the game). I have done everything I can find and none of it works. Is there anything I can do to fix this?

**Comment by Ryoumekono** [comment]
is there anytihing to do with honkai star rail?

**Comment by tsumeru39** [comment]
Now that I realise that there is a separate software for Star Rail, trying to run the mods through GIMI was kind of a dumb idea. But after deleting it I didn't retrieve the file from my recycle bin, I downloaded from here. I think it does have something to do with star rail...

**Comment by tsumeru39** [comment]
...tried using the srmi on star rail and... even THAT doesn't work. and NO, I am NOT turning off any malware protection to get this to work.

**Comment by HailstormVal** [comment]
I just cant get gimi to work

**Comment by leotorrez** [comment]
Did you install the HSR mods into your Genshin mod folder? If that's the case they could be causing issues
