### ISSUE TITLE
Error compiling custom shader, help.hlsl:1:1: E5000:syntax error, unexpected KW_BUFFER

### ISSUE THREAD

**Issue by Rullix** [SilentNightSound/GI-Model-Importer#106]
I run "3DMigoto Loader.exe" first, and it prints "Now run the game", so I launch the game. "3DMigoto Loader.exe" does its job and automatically quits, but the game prints "Error compiling custom shader " and won't enter the loading scene, after a while the game quits by itself. 
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/78005758/8a44ecee-41e5-4411-b4c1-9a3b42f0760b)
Here's more information:
Linux Mint 20.1
Wine-GE-Proton 8-2
dxvk-gplasync-2.2-1
Grasscutter 1.6.1-d9e8810
An anime game launcher 3.7.0

I spent a whole afternoon but still can't figure out what was wrong, please help!
PS: The game works fine if I don't run "3DMigoto Loader.exe" first.

**Comment by Rullix** [comment]
Update:  I couldn't fix the issue but I got my Mods working. It seems that the "help" Mod is having compatibility issues with Linux. I don't understand its code so I can't fix it. My workaround is to use the bo3b's version of 3dmigoto and install Mods manually.

**Comment by null-von-sushi** [comment]
Can you confirm whether [this](https://github.com/bo3b/3Dmigoto) is what you're talking about?
Because that repo last had a release in 2018? Or is there another repo?

**Comment by null-von-sushi** [comment]
For anyone that's trying to run this on Linux for the Anime Game, I was pointed to [this repo](https://github.com/MrLGamer/GIMI-for-Linux) which wroked for me.
