### ISSUE TITLE
F6 breaking mods but not disabling them

### ISSUE THREAD

**Issue by ThatOneDegen** [SilentNightSound/GI-Model-Importer#109]
title says it all

**Comment by shimizu-izumi** [comment]
Can confirm
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/53613583/93e5e216-76c0-428f-9f2b-8f2cc26dc4ae)

**Comment by Jadoofer** [comment]
yeah for me holding F9 works to disable it but its not a toggle, you have to press and hold it

**Comment by EnvySunrise** [comment]
Same problem here :/

**Comment by EnvySunrise** [comment]
I found a fix for that. Disable the mods with F6, then press F10, it will refresh and turn the mods back on. Then, the next time you'll hit F6 it should be good.

**Comment by leotorrez** [comment]
it is a known issue and its cause unknown. You can do as the last comment suggedted or open dev console with numpad 0 hold f9 and tap 0 again to disable mods

**Comment by leotorrez** [comment]
Issue can't be fixed at the current time. Alternative fix given to the user
