### ISSUE TITLE
请问hash_info.json是什么？

### ISSUE THREAD

**Issue by cenocean** [SilentNightSound/GI-Model-Importer#11]
本人是个小白，网上找了一大圈也没有找到答案，实在不知道该怎么办了QAQ
![Blender信息日志 10_7_2022 下午8_22_21](https://user-images.githubusercontent.com/109026687/178144802-54046090-5f66-4ec8-a0f8-16fd0dc3f14a.png)
，

**Comment by SilentNightSound** [comment]
确保您使用的是最新的 hash_info.json (https://github.com/SilentNightSound/GI-Model-Importer/blob/main/CharacterData/hash_info.json) 并且它位于这样的字符文件夹旁边
![image](https://user-images.githubusercontent.com/107697535/178149820-e25f9337-db29-4447-a4ac-3a31b6f6d01e.png)

**Comment by cenocean** [comment]
谢谢大佬，已经解决
