### ISSUE TITLE
YaoYao Blossoming mod Body Transparency Bug

### ISSUE THREAD

**Issue by sonamu-kr** [SilentNightSound/GI-Model-Importer#117]
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/141657739/5ac47afc-16c3-459b-910b-5783aba2af11)

always thanks to make mod
plz fix this bug, plz

**Comment by leotorrez** [comment]
If the mod is broken try to contact the author of the mod to have it fixed.

Alternatively you can try restarting the game or teleporting away so the game reloads the resources of Yao Yao in this case.
