### ISSUE TITLE
genshin_merge_mods.py trying to handling desktop.ini

### ISSUE THREAD

**Issue by Insiro** [SilentNightSound/GI-Model-Importer#121]
genshin_merge_mods.py try to rename desktop.ini
this file is windows directory configuration file, cannot handle on windows terminal
it required to ignored

**Comment by Insiro** [comment]
i make PR, please check
https://github.com/SilentNightSound/GI-Model-Importer/pull/120

**Comment by leotorrez** [comment]
Download latest version. it has been patched in v3
