### ISSUE TITLE
fps drop when using 3dmigoto

### ISSUE THREAD

**Issue by 1q84ltd** [SilentNightSound/GI-Model-Importer#122]
I am using fps unlock to get higher fps( >20). But, I have a question, it looks like when you using fps unlock + 3dmigo, it will drop 20-80 fps compare with using fps unlock alone. In addition,the fps is unstable when using 3dmigo+fps unlock

**Comment by leotorrez** [comment]
there could be conflicts between the two tools for sure. Do check how many fps does migoto take from your performance when running alone. It may be that you just have a lot of mods
