### ISSUE TITLE
I get an Error 

### ISSUE THREAD

**Issue by Shinimi** [SilentNightSound/GI-Model-Importer#125]
d3d11.dll description: "Direct3D 11 Runtime"
ERROR: The requested module "d3d11.dll" is not 3DMigoto
Please ensure that [Loader] "module" is set correctly and the DLL is in place.
Press enter to close...
ı get that error when ı try to open
3dmigito
and ı have "d3d11.dll"

![Screenshot_2](https://github.com/SilentNightSound/GI-Model-Importer/assets/143120483/723bd5a3-ea9c-4477-a85a-1b12509e185a)
![Screenshot_1](https://github.com/SilentNightSound/GI-Model-Importer/assets/143120483/43f65caf-b6db-456a-a314-0b1bb195bd2e)

**Comment by ZXNova** [comment]
I also get the same error

**Comment by ZXNova** [comment]
> I also get the same error
> 
> EDIT
> 
> I just went into the ini and used ctrl+F and looked for this line module = d3d11.ini and changed it to 3dmigoto.dll and then changed the name of d3d11.dll in the directory to 3dmigoto.dll

It still does not seem to be working. It runs, I hear two beep noises, and then the game doesn't start

**Comment by leotorrez** [comment]
Please come to the #verification-support channel in https://discord.gg/agmg if you need further help. For now, I suggest that you get the latest GIMI release and re-extract your GIMI zip file in case of corrupted data. If this does not work, try moving the GIMI folder to a different place as the current folder it is in may have restricted permissions.
