### ISSUE TITLE
The Loader is not configured correctly

### ISSUE THREAD

**Issue by R3ez** [SilentNightSound/GI-Model-Importer#126]
I got this error when i run the Loader.

The Loader is not configured correctly. Please copy the 3DMigoto d3d11.dll
and d3dx.ini into this directory, then edit the d3dx.ini's [Loader] section
to set the target executable and 3DMigoto module name.

Unable to open d3dx.ini
How can i solve it?

**Comment by leotorrez** [comment]
First some basic troubleshooting. Do not put migoto into the game folder cause it wont work and it will be flagged as hacks. Secondly try a fresh install of migoto. Third you can open d3dx.ini with a text editor

**Comment by Th3Legend27x100** [comment]
Im having this problem and that solution isnt rlly giving me enough to go off of
