### ISSUE TITLE
Change the style

### ISSUE THREAD

**Issue by Mlorping545** [SilentNightSound/GI-Model-Importer#128]
I recently download de mod of shogun raiden but, how can i change the models, e.g (differents aspects just de images

**Comment by skorpionred100** [comment]
eso suele estar especificado en la pagina o en el archivo que hayas descargado

**Comment by leotorrez** [comment]
to modify the textures you can use paint.net, photoshop or similar image edition software. As for the 3d model you will have to request the mod maker to share their project files. The mod can't be modified directly
