### ISSUE TITLE
Detected as trojan by windows defender

### ISSUE THREAD

**Issue by wafflesssssssss** [SilentNightSound/GI-Model-Importer#130]
This is more likely just to do with how the importer itself functions in tandem with genshin, though downloading it prompts windows defender to block it as it is detected as a trojan virus?

**Comment by leotorrez** [comment]
It's most likely a false positive, here a guide on how to report them or send the file for inspection: [https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide)

**Comment by DTWONE** [comment]
Sorry but i just download it and put it in virus total and it says there's this in the file Trojan.Malware.300983.susgen 
https://www.virustotal.com/gui/file/554eb6f2d9e6747b632fd362a221fa5432884c315742a7326a970a5e9b6c6e2d

**Comment by SilentNightSound** [comment]
Yes - with virus total, any time you see <8 or so results (out of 60+) it tends to be a false positive - many of the scanners it uses are very sensitive and will trigger on any exe you send. 1 out of 63 flagging it is about as good a score as you can possibly get (for reference, I often put in exe from trusted companies and get 4-5).

Any exe from this github or from trusted sources on gamebanana should be safe.

Also, susgen is a such great name lol
