### ISSUE TITLE
Merge issue: Textures Bugged

### ISSUE THREAD

**Issue by agarcia-imt** [SilentNightSound/GI-Model-Importer#133]
I successfully merged 2 mods.

But I found that the textures got messed up. It's not a problem of the mods because they were looking good on its own.

<a href="https://imagetwist.com/ph3bv9yk3qwe/yelanTextureBugged.png"><img src="https://s10.imagetwist.com/th/58093/ph3bv9yk3qwe.jpg" /></a>

Any suggestion on how to fix it?

**Comment by leotorrez** [comment]
rename texture files around till they match with their newfound slots

if it doesn't work send merged.ini here for closer inspection
