### ISSUE TITLE
does anyway to change mod default keyswap?

### ISSUE THREAD

**Issue by acer1204** [SilentNightSound/GI-Model-Importer#137]
i download a mod. 
the mod can use key swap to switch five mods.
it default is use 0, when i use "key h" to change next mod.
if i  press F10, the will auto use 0 mod,
it's anyway to edit order with merged.ini?

**Comment by leotorrez** [comment]
replace 

global $swapvar = 0

with

global persist $swapvar = 0

so the mod saves the value across playing sessions
