### ISSUE TITLE
ningguang orchidmod doesn't works

### ISSUE THREAD

**Issue by berry2130** [SilentNightSound/GI-Model-Importer#138]
Only the color changes of the face

; NingguangOrchid

; Overrides -------------------------

[TextureOverrideNingguangOrchidPosition]
hash = db37b198
vb0 = ResourceNingguangOrchidPosition

[TextureOverrideNingguangOrchidBlend]
hash = a8246d4a
vb1 = ResourceNingguangOrchidBlend
handling = skip
draw = 20739,0 

[TextureOverrideNingguangOrchidTexcoord]
hash = 396aa3ec
vb1 = ResourceNingguangOrchidTexcoord

[TextureOverrideNingguangOrchidVertexLimitRaise]
hash = 10de9c78

[TextureOverrideNingguangOrchidIB]
hash = f1d09b47
handling = skip
drawindexed = auto

[TextureOverrideNingguangOrchidHead]
hash = f1d09b47
match_first_index = 0
ib = ResourceNingguangOrchidHeadIB
ps-t0 = ResourceNingguangOrchidHeadDiffuse
ps-t1 = ResourceNingguangOrchidHeadLightMap
ps-t2 = ResourceNingguangOrchidHeadMetalMap
ps-t3 = ResourceNingguangOrchidHeadShadowRamp

[TextureOverrideNingguangOrchidBody]
hash = f1d09b47
match_first_index = 43539
ib = ResourceNingguangOrchidBodyIB
ps-t0 = ResourceNingguangOrchidBodyDiffuse
ps-t1 = ResourceNingguangOrchidBodyLightMap
ps-t2 = ResourceNingguangOrchidBodyMetalMap
ps-t3 = ResourceNingguangOrchidBodyShadowRamp

[TextureOverrideNingguangOrchidDress]
hash = f1d09b47
match_first_index = 56124
ib = ResourceNingguangOrchidDressIB
ps-t0 = ResourceNingguangOrchidDressDiffuse
ps-t1 = ResourceNingguangOrchidDressLightMap
ps-t2 = ResourceNingguangOrchidDressMetalMap
ps-t3 = ResourceNingguangOrchidDressShadowRamp

[TextureOverrideNingguangOrchidFaceHeadDiffuse]
hash = 4cc85338
ps-t0 = ResourceNingguangOrchidFaceHeadDiffuse

; Resources -------------------------

[ResourceNingguangOrchidPosition]
type = Buffer
stride = 40
filename = NingguangOrchidPosition.buf

[ResourceNingguangOrchidBlend]
type = Buffer
stride = 32
filename = NingguangOrchidBlend.buf

[ResourceNingguangOrchidTexcoord]
type = Buffer
stride = 20
filename = NingguangOrchidTexcoord.buf

[ResourceNingguangOrchidHeadIB]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = NingguangOrchidHead.ib

[ResourceNingguangOrchidBodyIB]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = NingguangOrchidBody.ib

[ResourceNingguangOrchidDressIB]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = NingguangOrchidDress.ib

[ResourceNingguangOrchidHeadDiffuse]
filename = NingguangOrchidHeadDiffuse.dds

[ResourceNingguangOrchidHeadLightMap]
filename = NingguangOrchidHeadLightMap.dds

[ResourceNingguangOrchidHeadMetalMap]
filename = NingguangOrchidHeadMetalMap.dds

[ResourceNingguangOrchidHeadShadowRamp]
filename = NingguangOrchidHeadShadowRamp.jpg

[ResourceNingguangOrchidBodyDiffuse]
filename = NingguangOrchidBodyDiffuse.dds

[ResourceNingguangOrchidBodyLightMap]
filename = NingguangOrchidBodyLightMap.dds

[ResourceNingguangOrchidBodyMetalMap]
filename = NingguangOrchidBodyMetalMap.dds

[ResourceNingguangOrchidBodyShadowRamp]
filename = NingguangOrchidBodyShadowRamp.jpg

[ResourceNingguangOrchidDressDiffuse]
filename = NingguangOrchidDressDiffuse.dds

[ResourceNingguangOrchidDressLightMap]
filename = NingguangOrchidDressLightMap.dds

[ResourceNingguangOrchidDressMetalMap]
filename = NingguangOrchidDressMetalMap.dds

[ResourceNingguangOrchidDressShadowRamp]
filename = NingguangOrchidDressShadowRamp.jpg

[ResourceNingguangOrchidFaceHeadDiffuse]
filename = NingguangOrchidFaceHeadDiffuse.dds

**Comment by leotorrez** [comment]
the following ini works for 4.1
```ini
; NingguangOrchid

; Overrides -------------------------

[TextureOverrideNingguangOrchidPosition]
hash = db37b198
vb0 = ResourceNingguangOrchidPosition

[TextureOverrideNingguangOrchidBlend]
hash = a8246d4a
vb1 = ResourceNingguangOrchidBlend
handling = skip
draw = 15835,0 

[TextureOverrideNingguangOrchidTexcoord]
hash = 396aa3ec
vb1 = ResourceNingguangOrchidTexcoord

[TextureOverrideNingguangOrchidVertexLimitRaise]
hash = 10de9c78

[TextureOverrideNingguangOrchidIB]
hash = f1d09b47
handling = skip
drawindexed = auto

[TextureOverrideNingguangOrchidHead]
hash = f1d09b47
match_first_index = 0
ib = ResourceNingguangOrchidHeadIB
ps-t0 = ResourceNingguangOrchidHeadDiffuse
ps-t1 = ResourceNingguangOrchidHeadLightMap
ps-t4 = ResourceNingguangOrchidHeadShadowRamp

[TextureOverrideNingguangOrchidBody]
hash = f1d09b47
match_first_index = 43539
ib = ResourceNingguangOrchidBodyIB
ps-t0 = ResourceNingguangOrchidBodyDiffuse
ps-t1 = ResourceNingguangOrchidBodyLightMap


[TextureOverrideNingguangOrchidDress]
hash = f1d09b47
match_first_index = 56124
ib = ResourceNingguangOrchidDressIB
ps-t0 = ResourceNingguangOrchidDressDiffuse
ps-t1 = ResourceNingguangOrchidDressLightMap

[TextureOverrideNingguangOrchidFaceHeadDiffuse]
hash = 4cc85338
ps-t0 = ResourceNingguangOrchidFaceHeadDiffuse
[TextureOverrideNingguangOrchidFaceHeadDiffuseFar]
hash = 08020bb1
ps-t0 = ResourceNingguangOrchidFaceHeadDiffuse


; Resources -------------------------

[ResourceNingguangOrchidPosition]
type = Buffer
stride = 40
filename = NingguangOrchidPosition.buf

[ResourceNingguangOrchidBlend]
type = Buffer
stride = 32
filename = NingguangOrchidBlend.buf

[ResourceNingguangOrchidTexcoord]
type = Buffer
stride = 20
filename = NingguangOrchidTexcoord.buf

[ResourceNingguangOrchidHeadIB]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = NingguangOrchidHead.ib

[ResourceNingguangOrchidBodyIB]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = NingguangOrchidBody.ib

[ResourceNingguangOrchidDressIB]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = NingguangOrchidDress.ib

[ResourceNingguangOrchidHeadDiffuse]
filename = NingguangOrchidHeadDiffuse.dds

[ResourceNingguangOrchidHeadLightMap]
filename = NingguangOrchidHeadLightMap.dds

[ResourceNingguangOrchidHeadMetalMap]
filename = NingguangOrchidHeadMetalMap.dds

[ResourceNingguangOrchidHeadShadowRamp]
filename = NingguangOrchidHeadShadowRamp.jpg

[ResourceNingguangOrchidBodyDiffuse]
filename = NingguangOrchidBodyDiffuse.dds

[ResourceNingguangOrchidBodyLightMap]
filename = NingguangOrchidBodyLightMap.dds

[ResourceNingguangOrchidBodyMetalMap]
filename = NingguangOrchidBodyMetalMap.dds

[ResourceNingguangOrchidBodyShadowRamp]
filename = NingguangOrchidBodyShadowRamp.jpg

[ResourceNingguangOrchidDressDiffuse]
filename = NingguangOrchidDressDiffuse.dds

[ResourceNingguangOrchidDressLightMap]
filename = NingguangOrchidDressLightMap.dds

[ResourceNingguangOrchidDressMetalMap]
filename = NingguangOrchidDressMetalMap.dds

[ResourceNingguangOrchidDressShadowRamp]
filename = NingguangOrchidDressShadowRamp.jpg

[ResourceNingguangOrchidFaceHeadDiffuse]
filename = NingguangOrchidFaceHeadDiffuse.dds


; .ini generated by GIMI (Genshin-Impact-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord

; 4.1 Character Fix 
[TextureOverride41FixVertexLimitRaise]
hash = 993bb35f

```
