### ISSUE TITLE
3d migoto messing up character models

### ISSUE THREAD

**Issue by Aethisc0ol** [SilentNightSound/GI-Model-Importer#139]
3d migoto doesnt seem to work in 4.1 at the moment reinstalling did not work and trying other mods didnt work either

**Comment by eg13eg** [comment]
ME TOO

**Comment by SilentNightSound** [comment]
https://gamebanana.com/tools/14912

**Comment by Aethisc0ol** [comment]
thank you for the help i didnt expect a response so fast

**Comment by h223chen** [comment]
amazing! super fast turnaround 🙏 🙏
