### ISSUE TITLE
The game closes just before the loading screen opens the map

### ISSUE THREAD

**Issue by Rimuti** [SilentNightSound/GI-Model-Importer#140]
I've already tried the tutorials, the videos, uninstalling and installing the game, uninstalling and installing 3dmigoto, deactivating mods and NOTHING. The game works normally without this, but just open the program and it slows down and there is a problem with it stopping at the loading screen, right in the middle of the GEO element. The worst that happens is that he finishes and comes back halfway through, but with the music in the background. Need help ;-;

**Comment by leotorrez** [comment]
try holding f9 when you hear the music. f9 is to deactivate mods temporarily. Might be there is a mod breaking the rendering.

Alternatively try loading a fresh install of 3dm to make sure no mod nor shader fix is causing issues
