### ISSUE TITLE
The Fischl-FallenAngelOutfitMod-Wings-MYRECOLOR don't work 

### ISSUE THREAD

**Issue by Kiss-Shot27** [SilentNightSound/GI-Model-Importer#141]
I have downloaded a mod and I have all the files but the program does not load it,
the creator cread this 
Please i need help for this and for other mod created with blender I don't know how to make it implemented with 3dmigoto loader

Thanks in advance. 

; Fischl
; Overrides -------------------------

[TextureOverrideFischlPosition]
hash = 9838aedf
vb0 = ResourceFischlPosition

[TextureOverrideFischlBlend]
hash = 0d1c1932
vb1 = ResourceFischlBlend
handling = skip
draw = 11396,0 

[TextureOverrideFischlTexcoord]
hash = d451d8d8
vb1 = ResourceFischlTexcoord

[TextureOverrideFischlVertexLimitRaise]
hash = 6c491d3b

[TextureOverrideFischlIB]
hash = 5cfc7a92
handling = skip
drawindexed = auto

[TextureOverrideFischlHead]
hash = 5cfc7a92
match_first_index = 0
ib = ResourceFischlHeadIB
ps-t0 = ResourceFischlHeadDiffuse
ps-t1 = ResourceFischlHeadLightMap
ps-t2 = ResourceFischlHeadShadowRamp

[TextureOverrideFischlBody]
hash = 5cfc7a92
match_first_index = 11535
ib = ResourceFischlBodyIB
ps-t0 = ResourceFischlBodyDiffuse
ps-t1 = ResourceFischlBodyLightMap
ps-t2 = ResourceFischlBodyMetalMap
ps-t3 = ResourceFischlBodyShadowRamp

[TextureOverrideFischlDress]
hash = 5cfc7a92
match_first_index = 42471
ib = ResourceFischlDressIB
ps-t0 = ResourceFischlDressDiffuse
ps-t1 = ResourceFischlDressLightMap
ps-t2 = ResourceFischlDressShadowRamp

; Resources -------------------------

[ResourceFischlPosition]
type = Buffer
stride = 40
filename = FischlPosition.buf

[ResourceFischlBlend]
type = Buffer
stride = 32
filename = FischlBlend.buf

[ResourceFischlTexcoord]
type = Buffer
stride = 20
filename = FischlTexcoord.buf

[ResourceFischlHeadIB]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = FischlHead.ib

[ResourceFischlBodyIB]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = FischlBody.ib

[ResourceFischlDressIB]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = FischlDress.ib

[ResourceFischlHeadDiffuse]
filename = FischlHeadDiffuse.dds

[ResourceFischlHeadLightMap]
filename = FischlHeadLightMap.dds

[ResourceFischlHeadShadowRamp]
filename = FischlHeadShadowRamp.jpg

[ResourceFischlBodyDiffuse]
filename = FischlBodyDiffuse.dds

[ResourceFischlBodyLightMap]
filename = FischlBodyLightMap.dds

[ResourceFischlBodyMetalMap]
filename = FischlBodyMetalMap.dds

[ResourceFischlBodyShadowRamp]
filename = FischlBodyShadowRamp.jpg

[ResourceFischlDressDiffuse]
filename = FischlDressDiffuse.dds

[ResourceFischlDressLightMap]
filename = FischlDressLightMap.dds

[ResourceFischlDressShadowRamp]
filename = FischlDressShadowRamp.jpg

; .ini generated by GIMI (Genshin-Impact-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord

**Comment by leotorrez** [comment]
mods broke in 4.1 try the fix for them: https://gamebanana.com/tools/14912

**Comment by SilentNightSound** [comment]
This is a pre 4.1 mod yes. If you run the fix leo linked, it will fix it.

**Comment by Kiss-Shot27** [comment]
Thanks yes i found this 4.1 parch few days ago.
Thanks for all and go to close this case
