### ISSUE TITLE
horror fuel Lumine (red abyss costume)

### ISSUE THREAD

**Issue by Clover696969** [SilentNightSound/GI-Model-Importer#146]
my cutscenes r so cursed with this
I can only see lumine's face and absolutely nothing else (very skeri)
idk pls help lol

╰（‵□′）╯

; TravelerGirl

; Overrides -------------------------

[TextureOverrideTravelerGirlPosition]
hash = 8239be13
vb0 = ResourceTravelerGirlPosition

[TextureOverrideTravelerGirlBlend]
hash = 8772fa81
vb1 = ResourceTravelerGirlBlend
handling = skip
draw = 37194,0 

[TextureOverrideTravelerGirlTexcoord]
hash = 8d2c7c7c
vb1 = ResourceTravelerGirlTexcoord

[TextureOverrideTravelerGirlVertexLimitRaise]
hash = 0d8adebb

[TextureOverrideTravelerGirlIB]
hash = dfb54407
handling = skip
drawindexed = auto

[TextureOverrideTravelerGirlHead]
hash = dfb54407
match_first_index = 0
ib = ResourceTravelerGirlHeadIB
ps-t0 = ResourceTravelerGirlHeadDiffuse
ps-t1 = ResourceTravelerGirlHeadLightMap
ps-t2 = ResourceTravelerGirlHeadShadowRamp

[TextureOverrideTravelerGirlBody]
hash = dfb54407
match_first_index = 6915
ib = ResourceTravelerGirlBodyIB
ps-t0 = ResourceTravelerGirlBodyDiffuse
ps-t1 = ResourceTravelerGirlBodyLightMap
ps-t2 = ResourceTravelerGirlBodyMetalMap
ps-t3 = ResourceTravelerGirlBodyShadowRamp

[TextureOverrideTravelerGirlDress]
hash = dfb54407
match_first_index = 40413
ib = ResourceTravelerGirlDressIB
ps-t0 = ResourceTravelerGirlDressDiffuse
ps-t1 = ResourceTravelerGirlDressLightMap
ps-t2 = ResourceTravelerGirlDressMetalMap
ps-t3 = ResourceTravelerGirlDressShadowRamp

[TextureOverrideTravelerGirlFaceHeadDiffuse]
hash = cdabcf6f
ps-t0 = ResourceTravelerGirlFaceHeadDiffuse

; Resources -------------------------

[ResourceTravelerGirlPosition]
type = Buffer
stride = 40
filename = TravelerGirlPosition.buf

[ResourceTravelerGirlBlend]
type = Buffer
stride = 32
filename = TravelerGirlBlend.buf

[ResourceTravelerGirlTexcoord]
type = Buffer
stride = 20
filename = TravelerGirlTexcoord.buf

[ResourceTravelerGirlHeadIB]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = TravelerGirlHead.ib

[ResourceTravelerGirlBodyIB]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = TravelerGirlBody.ib

[ResourceTravelerGirlDressIB]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = TravelerGirlDress.ib

[ResourceTravelerGirlHeadDiffuse]
filename = TravelerGirlHeadDiffuse.dds

[ResourceTravelerGirlHeadLightMap]
filename = TravelerGirlHeadLightMap.dds

[ResourceTravelerGirlHeadShadowRamp]
filename = TravelerGirlHeadShadowRamp.jpg

[ResourceTravelerGirlBodyDiffuse]
filename = TravelerGirlDressDiffuse.dds

[ResourceTravelerGirlBodyLightMap]
filename = TravelerGirlDressLightMap.dds

[ResourceTravelerGirlBodyMetalMap]
filename = TravelerGirlBodyMetalMap.dds

[ResourceTravelerGirlBodyShadowRamp]
filename = TravelerGirlBodyShadowRamp.jpg

[ResourceTravelerGirlDressDiffuse]
filename = TravelerGirlDressDiffuse.dds

[ResourceTravelerGirlDressLightMap]
filename = TravelerGirlDressLightMap.dds

[ResourceTravelerGirlDressMetalMap]
filename = TravelerGirlDressMetalMap.dds

[ResourceTravelerGirlDressShadowRamp]
filename = TravelerGirlDressShadowRamp.jpg

[ResourceTravelerGirlFaceHeadDiffuse]
filename = TravelerGirlFaceHeadDiffuse.dds

; .ini generated by GIMI (Genshin-Impact-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord

; 4.1 Character Fix 
[TextureOverride41FixVertexLimitRaise0]
hash = 846ff19c

**Comment by leotorrez** [comment]
It looks mostly fine. The two parts that could be causing issues is the old VertexLimitIncrease and the faceheaddiffuse. try removing those one at the time and see if it fixes the issue. 

Can't help much more without a link to the original mod

**Comment by Clover696969** [comment]
> It looks mostly fine. The two parts that could be causing issues is the old VertexLimitIncrease and the faceheaddiffuse. try removing those one at the time and see if it fixes the issue.
> 
> Can't help much more without a link to the original mod

thankyou for ur reply, 

https://gamebanana.com/mods/421157
this is the link
