### ISSUE TITLE
how can i solve this problem

### ISSUE THREAD

**Issue by Zhang2003** [SilentNightSound/GI-Model-Importer#147]
<img width="896" alt="image" src="https://github.com/SilentNightSound/GI-Model-Importer/assets/146909944/86ea9ce7-ccf6-4c62-b860-a034381bf34c">

**Comment by SilentNightSound** [comment]
Make sure to transfer custom properties from the 3dmigoto object to your new one (or better yet, merge your new object into the 3dmigoto one).
