### ISSUE TITLE
Bugged map

### ISSUE THREAD

**Issue by alhaitham157** [SilentNightSound/GI-Model-Importer#149]
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/148434672/f39ed547-94c6-44db-a7c7-6327dc2dfc1f)

Whenever I use this Wriothesley mod the map has some weird textures going on and it really bothers me so is there any way to fix it? Im not really good with these stuff

**Comment by SilentNightSound** [comment]
Double check this guide to see: https://gamebanana.com/tuts/16515. Most likely the modder who made the Wriothesley mod is using an outdated script to fix reflections
