### ISSUE TITLE
Some minor questions about 3DMITOGO

### ISSUE THREAD

**Issue by thestmitsuki** [SilentNightSound/GI-Model-Importer#151]
Hi, this is an awesome project

I saw in the readme that 

"GIMI is a version of 3DMigoto that I have modified to be compatible with Genshin. "

But I searched through the whole repository and found mostly python files. Where can I get the modified 3DMigoto source code for research? Or did I miss something?

**Comment by leotorrez** [comment]
The source code is not posted here. Just the usable tools. You will have to contact SilentNightSound for the source code
