### ISSUE TITLE
 hide these warnings ?

### ISSUE THREAD

**Issue by Yangao8226** [SilentNightSound/GI-Model-Importer#154]
May I ask how to hide these warnings? These warnings do not actually affect my mod operation
![20231026141912](https://github.com/SilentNightSound/GI-Model-Importer/assets/113701746/cd074cd3-a5f2-405a-9d6b-e5c4a42de6cb)

**Comment by Yangao8226** [comment]
Every time my warning is displayed in the upper left corner for a long time, which greatly affects the appearance Q.Q

**Comment by leotorrez** [comment]
either fix the issue in the ini that causes the error or set handling = 0 in d3dx.ini to ignore them(beep will still sound tho)

**Comment by Yangao8226** [comment]
> 要么修复 INI 中导致错误的问题，要么在 D0DX.ini 中设置 HANDLING = 3 以忽略它们（哔声仍然会响起）

I am very grateful for your answer, but handling=0 did not work. Maybe I don't know how to handle it

**Comment by Yangao8226** [comment]
> either fix the issue in the ini that causes the error or set handling = 0 in d3dx.ini to ignore them(beep will still sound tho)

I am very grateful for your answer, but handling=0 did not work. Maybe I don't know how to handle it

**Comment by Yangao8226** [comment]
After my unremitting efforts, I finally fixed it and solved QaQ using the dumbest method possible
