### ISSUE TITLE
the issue speaks for itself

### ISSUE THREAD

**Issue by srqtl** [SilentNightSound/GI-Model-Importer#157]
![resim_2023-11-06_171434224](https://github.com/SilentNightSound/GI-Model-Importer/assets/150047439/a337ca51-2851-47d8-a761-6c0a159c0471)
i dont have another instance opened
![resim_2023-11-06_171717278](https://github.com/SilentNightSound/GI-Model-Importer/assets/150047439/39394953-eecc-40f0-ab43-f6b7aae60096)
this also shows up for less then a second and instantly closes before the other instance error appears

**Comment by leotorrez** [comment]
try restarting your pc to ensure no other instance is running

**Comment by srqtl** [comment]
> try restarting your pc to ensure no other instance is running

i did multiple times, tried forcefully shutting it by cmd but it simply said no instance found
