### ISSUE TITLE
All load sceen and every hud is always full

### ISSUE THREAD

**Issue by Atomicboot** [SilentNightSound/GI-Model-Importer#158]
Every HUD that have a charge bar is always full, example is the stamina:
![1](https://github.com/SilentNightSound/GI-Model-Importer/assets/54910976/f521feda-7c56-4578-9533-6a977c9136d9)

or the HP bar, not having full hp but the bar is full:
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/54910976/4115c6d1-17d1-46e5-9818-f468dbc4956b)

same problem can be seen in the loading screen with all the loading bar always full even if is not full loaded

**Comment by leotorrez** [comment]
surely some shaderfix is breaking stuff. try moving those files outside of ShaderFixes folder to verify if that's the case

**Comment by Sakitoshi** [comment]
can confirm that some shaderfix files were the problem.
it happened to me after i punched in my card info to renew welkin, deleted the most recent shader fix files (that had a creation date and time of when i put my card info) and everything went back to normal after pressing F10.
