### ISSUE TITLE
Honkai SR update 1.5 fps gone

### ISSUE THREAD

**Issue by Doktorishka2** [SilentNightSound/GI-Model-Importer#159]
Honkai Star Rail, since the update 1.5, FPS drops to 22(total unplayable). FPS drop starts from launching the game. Without 3dmigoto loader, 60 fps without issues. With the previous version of the game, didn't had this issue. Checked on Epic and official versions. May a fix for this issue?

**Comment by leotorrez** [comment]
Try again without mods in your /mods folder and no shaderfixes in /ShaderFixes to make sure none of them are causing the issue

**Comment by Doktorishka2** [comment]
> Try again without mods in your /mods folder and no shaderfixes in /ShaderFixes to make sure none of them are causing the issue

Have tried without mods and shader fixes as u said (both folders are empty now) ---- No changes.

**Comment by Doktorishka2** [comment]
> I've loaded the game myself with the program and noticed no significant FPS change compared to previous versions. The only thing that I can maybe think of is that the game reset the graphic registry options in 1.5 - if you were controlling the fps by modifying the registry instead of the in-game settings, check the option is still there. Try a fresh version of the program? Maybe it has been corrupted somehow

I don't use any fps change programs. Just the game settings. Where can I get "fresh version of the program"? I see in the files that they are 7 months old, and no new versions. Which I use is the same.
![srmi](https://github.com/SilentNightSound/GI-Model-Importer/assets/150930912/52208daa-d277-4870-aec4-5e13f7b35c50)

**Comment by leotorrez** [comment]
Interesting. 7 months old is the newer files we have. 

What are your system specs?

**Comment by Doktorishka2** [comment]
Specs are - Ryzen 3700x, 16gb ram, gtx 1080ti 11gb, win10x64.
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/150930912/5f55ae58-84c3-42f7-bfa8-fc9296395d8f)

**Comment by Doktorishka2** [comment]
So, any ideas?

**Comment by Doktorishka2** [comment]
Solved myself, problem was in VSync in the game settings. Turned it OFF and problem has gone.

**Comment by Doktorishka2** [comment]
Solved myself, problem was in VSync in the game settings. Turned it OFF and problem has gone.
