### ISSUE TITLE
[help] WARNING : Unrecognised entry ...

### ISSUE THREAD

**Issue by hasban12138** [SilentNightSound/GI-Model-Importer#172]
Mode link（mode连接）: https://gamebanana.com/mods/463563

Game ver（游戏版本）![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/33484052/41f572f4-e728-4af5-b651-06378a6b3a61)

Here is screenshot ，how can I fix this? （这是问题截图 我要怎样解决这个问题）
![QQ截图20231127031630](https://github.com/SilentNightSound/GI-Model-Importer/assets/33484052/15c47c3a-6211-4ef2-8084-5afbc1b55bbc)

**Comment by leotorrez** [comment]
Update GIMI. you have an old version

**Comment by wppkkr** [comment]
![Uploading QQ20240820-164554.png…]()
