### ISSUE TITLE
How to uninstall GIMI completely?

### ISSUE THREAD

**Issue by Litel909er** [SilentNightSound/GI-Model-Importer#175]
After using this mod, my start loading scene(after you enter the door) becomes unresponsive such that the cursor turns into blue circle and it happens multiple times, different from before i use the mod. Since it lengthen the loading times, I've since delete the mod but the issue still persist even after fully reinstalling genshin from scratch the issue still exist. I'm looking for possible fix, any help is appreciated!

Mod i used is transparency filter and adventure map+

**Comment by leotorrez** [comment]
Simply extract migoto into a new folder instead of your usual one. It will be a fresh install.

**Comment by Litel909er** [comment]
> Simply extract migoto into a new folder instead of your usual one. It will be a fresh install.

You misunderstand my problem.
My problem is that the mod still affect my game(slower loading) even though i have deleted the mod(also have done what you suggested) and reinstall the game.

**Comment by Litel909er** [comment]
![20231213_141407](https://github.com/SilentNightSound/GI-Model-Importer/assets/152581623/64a08cc0-7fb9-4e69-86a5-7361831e19cc)

It's fixed now, all I have to do is run compability troubleshooting
