### ISSUE TITLE
Skins are buggy

### ISSUE THREAD

**Issue by MrTraveler25** [SilentNightSound/GI-Model-Importer#182]
I follow the instructions regarding 3dmigoto installed. I have relocate all skins into the Mod section, and majority of the skins aren't coming up what i've expected. I've attach some screen shots.
![Keqing Skin](https://github.com/SilentNightSound/GI-Model-Importer/assets/154019891/2cafa19d-2055-499e-92c1-ca78cfcdab38)
![Barbara Skin](https://github.com/SilentNightSound/GI-Model-Importer/assets/154019891/53cb0ce4-ea8b-42c0-9da5-1c449cea9770)

**Comment by SilentNightSound** [comment]
Run the 4.1 fix https://gamebanana.com/tools/14912

**Comment by buffalodragon** [comment]
Since it's v4.3 now, you will need to use this tool: https://gamebanana.com/tools/15654
If it does not work, you will need to wait for the mod author to provide an update for 4.3. This isn't a GIMI issue.
