### ISSUE TITLE
bugged skin

### ISSUE THREAD

**Issue by genjifx** [SilentNightSound/GI-Model-Importer#184]
shinobu kocho skin is bugged while switching ayaka with shinobu kocho only her face appears is it a bug?
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/154275541/bdaf3360-1716-4581-87e1-081da68ed483)

**Comment by L1ttleCup** [comment]
u need find a mod named 4.3 fix
no good at english XD

**Comment by genjifx** [comment]
so they need to redo it for 4.3?

**Comment by Garwinium** [comment]
you can use [this tool](https://gamebanana.com/tools/15654) to fix the skin

**Comment by genjifx** [comment]
tried it didnt work maybe the owner of the mod did something wrong idk

**Comment by genjifx** [comment]
nvm just worked tysm for the help
