### ISSUE TITLE
bug skin

### ISSUE THREAD

**Issue by Aiko75** [SilentNightSound/GI-Model-Importer#186]
![Screenshot (135)](https://github.com/SilentNightSound/GI-Model-Importer/assets/154428591/1a607763-5ab9-4f4e-8b1b-9ee6d134dd3c)
![Screenshot (136)](https://github.com/SilentNightSound/GI-Model-Importer/assets/154428591/19138f68-5fd3-4481-a7b1-95f64e24a050)
i used 3dmigoto good,until today
all skin are getting like this
how i can fix?
p/s:i already used genshin update mod and its still like this

**Comment by Branmuffinland** [comment]
https://gamebanana.com/tools/15654

**Comment by buffalodragon** [comment]
If the above 4.3 patcher does not work, you will need to wait for the mod author to update your mod.
