### ISSUE TITLE
Skins not loading properly

### ISSUE THREAD

**Issue by Puffled2004** [SilentNightSound/GI-Model-Importer#187]
So i've been trying to download a mod for Scaramouche's old design as a skin, i tried 2 different mods for his fatui skin and both of them have him looking all messed up. the textures of his current Wanderer design mesh with the textures of the mod, he gets all stretched out and buggy. i've tried everything to fix this, i tried re-installing 3dmigoto and the mod, i tried different versions of the mod, i tried using older versions of migoto and the mod, i tried re-booting the game multiple times, teleporting away, refreshing the mod with F10, etc. Nothing works, he always loads with the textures messed up. 
![imagem_2023-12-22_160550362](https://github.com/SilentNightSound/GI-Model-Importer/assets/154629529/2e608921-68b7-4681-94c7-72fec2985e04)

Here's how he looks like, when he's supposed to just look like his old fatui design. Any idea of how i can fix this?

**Comment by Puffled2004** [comment]
BTW: i've used the 4.3 mod fixer and it *kinda* fixed, it loads normal now but after like 2 seconds it'll re-bug. if i swap to another char then back to him he's back to normal, but then bugs again after another 2 seconds.

**Comment by CrazyChloe03** [comment]
me too!!!

**Comment by kataura** [comment]
I'm having the same issue on only a couple characters like navia and raiden and apparently others are as well.

**Comment by buffalodragon** [comment]
You will need to either;

1. Use the 4.3 mod fixer to _hopefully_ fix your skins, or
2. Wait for the mod to be updated for 4.3.

This isn't a GIMI issue.
