### ISSUE TITLE
Add Batch Frame Analasys & Batch Collect

### ISSUE THREAD

**Issue by Morpho-Dee-EX** [SilentNightSound/GI-Model-Importer#188]
I've noticed that there is no option to select multiple or all frames to analyze. Adding in the aformentioned feature would greatly help those who want to dump entire towns into Blender, rather than having to filter one by one. And the batch collect would function in a similar way to the batch frame analasys, allowing multiple files that could be imported into Blender to be made at once. And perhaps, if this suggestion is implemented, add a method to prevent the character from being selected and then batch frame analasys.

(Side note: Instead of objects disappearing upon being selected with the Frame Analasys, add in a glow or something to show that its selected, without the model vanishing.)

**Comment by leotorrez** [comment]
These are innate functionalities form 3dmigoto rather than this genshin impact adaptation of the tool. However frame dump already supports multiframe dumping, just hold down f8.

As for multi object import into blender you will have to create a tool for such an end- I advice to look into bpy and 3dm multivb plugin

**Comment by Morpho-Dee-EX** [comment]
Ah, perhaps the multiframe dump should have been more obvious, or pointed out? And do you have a link to BPY and/or 3DM multivb? (The plugins)

**Comment by leotorrez** [comment]
bpy is blender own library you can find the docs in their website-

3dm multivb import: https://github.com/DarkStarSword/3d-fixes/blob/master/blender_3dmigoto.py
