### ISSUE TITLE
Toggle default skin of individual characters

### ISSUE THREAD

**Issue by MenonPlayz** [SilentNightSound/GI-Model-Importer#189]
Hello and merry christmas if u celebrate,

I was wondering whether GIMI allows use to toggle mods on and off for certain skins only.
Is there any way to do this?

**Comment by leotorrez** [comment]
As in setting the default skins as a toggle option? just set $swapvar to an invalida value and it will default to the normal skin.

for example in the key section you can modify it like so:

[KeySwap]
.......

$swapvar=1,2,3,-1

where -1 would be the invalid value
