### ISSUE TITLE
After using ORFix some characters' shadow broken

### ISSUE THREAD

**Issue by chchan1125** [SilentNightSound/GI-Model-Importer#190]
Like topic mentioned, after using ORFix, Dehya, Navia, Freminet  and Baizhu got correct display about the shadow in Character page. but others character's shadow got break. Otherwise, deleting ORFix the situation is completely different. Plz help!
(After deleting ORFix) 
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/154748108/1af5e1d4-bdbc-4f00-bb2f-dd334f7c7a70)
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/154748108/f6e5312e-7bf0-4f9d-9912-5cdd36d49bc4)
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/154748108/399bd03f-4f4d-4273-9d68-88102d51b1b8)
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/154748108/a24754ad-f468-4ddf-affb-95ff286c1286)

**Comment by leotorrez** [comment]
orfix related issues should go in github.com/leotorrez/LeoTools

I am the author of the tool so I will check on this- for the time being update the orfix.ini to make sure that is not the cause- if the issue persist open an issue at that repo- I will probably have a fix and already checked on this by then. Do not reply in this thread please
