### ISSUE TITLE
Mod Texture issues

### ISSUE THREAD

**Issue by Everelin** [SilentNightSound/GI-Model-Importer#193]
I have been trying to fix this thing even though its on the latest update but to no avail nothing I do works
![Genshin Impact Screenshot 2023 12 31 - 14 38 46 24](https://github.com/SilentNightSound/GI-Model-Importer/assets/155330034/401c2994-ce4b-47b9-aa18-3eeae4083ebc)
![Genshin Impact Screenshot 2023 12 31 - 14 38 13 98](https://github.com/SilentNightSound/GI-Model-Importer/assets/155330034/8206eb60-85a8-4274-8ae3-ad879f83c41f)

**Comment by RaSan147** [comment]
use the 4.3 patch

https://gamebanana           .com/tools/15654

**Comment by buffalodragon** [comment]
If the linked 4.3 patcher above doesn't work, you will need to wait for the mod author to update your mod for 4.3.
