### ISSUE TITLE
3dmigoto  run with other   tools or loaders Will lead to flashback

### ISSUE THREAD

**Issue by QINCHENG159** [SilentNightSound/GI-Model-Importer#199]
Starting two different loaders into the game will lead to flashback, and opening a loader alone will not cause flashback, and there is no startup error prompt.Starting two different loaders into the game will lead to flashback, and opening a loader alone will not cause flashback, and there is no startup error prompt.

**Comment by QINCHENG159** [comment]
just run the 3dmigoto loader first，Can also lead to startup failure.

**Comment by leotorrez** [comment]
discord.gg/agmg #Verification-support can help you out to get the loader started for the first time and troubleshooting issues
