### ISSUE TITLE
Error or Bug Skin Female Xingqiu

### ISSUE THREAD

**Issue by cadharist** [SilentNightSound/GI-Model-Importer#202]
I found a Bug or error in Xingqiu's skin MOD, exactly here: https://gamebanana.com/mods/454231

**Comment by leotorrez** [comment]
what bug tho-

**Comment by cadharist** [comment]
character render doesn't work, sorry for my English

Pada Jum, 26 Jan 2024 21.32, Leandro Torrez ***@***.***>
menulis:

**Comment by cadharist** [comment]
there are problems when rendering skins

**Comment by cadharist** [comment]
![like this](https://github.com/SilentNightSound/GI-Model-Importer/assets/120342535/68232f9f-576b-442d-ae39-c848170c8433)
It looks like this
