### ISSUE TITLE
Mod Problem

### ISSUE THREAD

**Issue by schlabuffke** [SilentNightSound/GI-Model-Importer#203]
![Bild_2024-01-26_192625340](https://github.com/SilentNightSound/GI-Model-Importer/assets/157836322/1f449de5-94b0-41c0-932d-729dc9acb911)

I have a problem with the Genshin Impact Mod https://gamebanana.com/mods/483338 .

**Comment by Leonhardt01** [comment]
@schlabuffke Bro, maybe you can find the answer here: https://gamebanana.com/tools/15654
