### ISSUE TITLE
what's the difference bewteen development version and playing one

### ISSUE THREAD

**Issue by Jamesme0** [SilentNightSound/GI-Model-Importer#204]
Idiot question, but the two version both have green text at top and bottom of the screen, 
besides it was written: (only if using the "for development" version, the "for playing" version does not show the green text). 
i am using the playing one but i also can see that, and i can open f1 green menu and use 123456798/*- things
plus i see the both versions of the README.txt describe themselves as development versions, but in the v6 GIMI, playing one described "release version ... for speed"
Just curiouos, i accidentally passed some num button then triggered something, i don't know what i had changed, i pass + to reset but still my stamina and hp showed abnormality.
So i have to delete this tool and download again, then wondering why playing vision has this function

**Comment by leotorrez** [comment]
the main difference is the hunting mode being disabled for playing version. thats about it.
