### ISSUE TITLE
It says that Migoto Loader is still running.

### ISSUE THREAD

**Issue by mastercheif1229** [SilentNightSound/GI-Model-Importer#206]
When I try to launch Migoto Loader, it says that it is still running, even after restarting my computer.

**Comment by DJLegends1011** [comment]
same

**Comment by 3058132083** [comment]
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/52588960/a4820aac-abce-46da-8acd-6190bcbe55a8)
Run as Administrator
