### ISSUE TITLE
no modded skin loading

### ISSUE THREAD

**Issue by Bunstry** [SilentNightSound/GI-Model-Importer#209]
added 2 mods: https://gamebanana.com/mods/465217 and https://gamebanana.com/mods/465870 but both don't wanna load no matter how many times i try to delete 1 of the 2 or how many times i press F10, evern tried clearing the Shaderfixes file but after many attempts of doing whatever i can, i gave up because i have been at it for almost 4 hours straight doing anything i can, starting the loader and booting up the game but never getting results,.
i just find it very strange because yesterday https://gamebanana.com/mods/465870 actually worked (sorta, the skin was a bit buggy) so i have no idea why it doesn't work suddenly.
if anyone is willing to help, thx in advance.

**Comment by leotorrez** [comment]
there was a recent break in mods. check discord server announcement

**Comment by Bunstry** [comment]
> there was a recent break in mods. check discord server announcement

may i ask for a link? feel like a massive idiot 'cause i can't find it. :/

**Comment by leotorrez** [comment]
> > there was a recent break in mods. check discord server announcement
> 
> may i ask for a link? feel like a massive idiot 'cause i can't find it. :/

Discord.gg/agmg
