### ISSUE TITLE
skins breaks every time I switch characters

### ISSUE THREAD

**Issue by loreimal** [SilentNightSound/GI-Model-Importer#211]
Whenever I switch characters the skin breaks, then it corrects itself after a few seconds?

Any idea what I am doing wrong? I've tried:

reinstalling GIMI
updating mod manager (JASM)
downloaded and applied the 4.4 fix
turned off dynamic character resolution

**Comment by leotorrez** [comment]
does it happen with all mods? or one in particular. If the second case, which mod is it?

**Comment by loreimal** [comment]
> does it happen with all mods? or one in particular. If the second case, which mod is it?

happens with all mods, im guessing something is wrong with the main folder

**Comment by leotorrez** [comment]
Could be a shader in /ShaderFixes messing with stuff. Try with a clean shaderfixes folder

**Comment by loreimal** [comment]
> Could be a shader in /ShaderFixes messing with stuff. Try with a clean shaderfixes folder

sorry if i sound like i dont know (cause i really dont xD) but how does one clean the shaderfixes folder

do I just replace everything in the folder with a copy from a new GIMI file? orr

**Comment by leotorrez** [comment]
yeah with files from a fresh download of the tool

**Comment by loreimal** [comment]
> yeah with files from a fresh download of the tool

aight that fixed the problem, Big Thanks !
