### ISSUE TITLE
The app keeps waiting for a program

### ISSUE THREAD

**Issue by Drone003** [SilentNightSound/GI-Model-Importer#214]
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/159717489/080b4159-ffb1-42be-b45a-d2aa8a82e3f5)
I tried looking at multiple tutorials but none of them have this issue and idk what to do

**Comment by leotorrez** [comment]
It is waiting for genshin to be launched. go to discord.gg/agmg for help on your first time using the tool. This issue chain is for issues related to the code not its usage
