### ISSUE TITLE
Using the 4.3 mods on older version. 

### ISSUE THREAD

**Issue by Tenseichh** [SilentNightSound/GI-Model-Importer#216]
Is it possible to use mods updated for version 4.3 in older versions, like 4.0 or 3.2?

**Comment by leotorrez** [comment]
yes- but you need to modify the 4.3 fix script to perform the reverse operation. At the moment there is not tool that does that on its own. But fixing the code for this purpose shouldn't be too hard. Check Gamebanana. Someone probably made it already
