### ISSUE TITLE
Mod broken on my pc

### ISSUE THREAD

**Issue by Jack203012** [SilentNightSound/GI-Model-Importer#219]
I try too install and reinstall this mod for many times. But some how it's still not working
now all my characters are look like this :
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/97491106/ce232d23-fbf8-445a-9d38-a04122d0c2a7)
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/97491106/a91d8476-a004-41e5-a7c8-7d2d60a98022)
how can i fix it now????
help me pls
btw, i had already use this https://gamebanana.com/tools/16084

**Comment by leotorrez** [comment]
since 4.4 you gotta turn off dynamic resolution
