### ISSUE TITLE
error on merging mod files - genshin_merge_mods.py

### ISSUE THREAD

**Issue by SuperPhenotype** [SilentNightSound/GI-Model-Importer#220]
Parsing ini sections
Calculating overrides and resources
Traceback (most recent call last):
  File "/var/home/superphenotype/Downloads/test/genshin_merge_mods.py", line 261, in <module>
    main()
  File "/var/home/superphenotype/Downloads/test/genshin_merge_mods.py", line 125, in main
    with open(f"{all_mod_data[i]['location']}\\{all_mod_data[i][command]}", "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './tester\\TravelerGirlPosition.buf'
--------------------

Genshin Impact: Error presents itself no matter which mods are present prior to merge attempt. Always the same .buf file.

fails to output a merged .ini file after complaining about not being able to locate the .buf file.
 
I've tried merge scripts supplied from other mods, from this git repo, at different times, written differently than the same script found on Main branch, it's always the same problem.

--------------------
![Merge-Error](https://github.com/SilentNightSound/GI-Model-Importer/assets/119357189/308d3837-3993-4e84-88b4-a47dc9fa8b4b)

**Comment by SuperPhenotype** [comment]
I've adjusted some of the python script in the Merge Utility. The utility now correctly parses ini files, and won't get hungup on complaining about missing files. The specific lines are line # 114 & line # 176. It's working for me.

![SS_INI_Parsing-Edits](https://github.com/SilentNightSound/GI-Model-Importer/assets/119357189/ffd5cd47-620e-4386-bea8-27fe4ac6d90f)

![SS_file_resource_adjust](https://github.com/SilentNightSound/GI-Model-Importer/assets/119357189/627edde1-85e2-4f85-9004-b32e543c8132)

**Comment by leotorrez** [comment]
The complaining is somewhat intended. Merge script was designed to merge mods created with the blender export. If a mod maker edits their mod after it was generated, the script will likely fail at merging it.
