### ISSUE TITLE
PLEASE FIX THIS BUG!!

### ISSUE THREAD

**Issue by cadharist** [SilentNightSound/GI-Model-Importer#221]
https://gamebanana.com/mods/download/446772#
She lost her legs LMAO. Even I have applied the fix app, again and again.
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/120342535/7a86e799-6a0b-4e3c-8e25-dcb4b168e724)

**Comment by leotorrez** [comment]
tp

**Comment by cadharist** [comment]
> tp

??? what do you mean? i don't understand it. i'm noob in english.

**Comment by leotorrez** [comment]
teleport away so the character model reloads. or restart game
