### ISSUE TITLE
Potential Update Caused GIMI to Stop Working Entirely

### ISSUE THREAD

**Issue by JIceberg** [SilentNightSound/GI-Model-Importer#229]
I recently had all mods working until my PC crashed last night and force updated. I am using a Windows 11 computer. Now, nothing I do works whatsoever. I have installed a fresh version of GIMI onto my device and tried testing to see if a mod would work and nothing will load. I can tell that GIMI is running because the help popup appears, and when I press F10 I can hear the "update" noise  indicating that it is attempting to import/reload the models. However, nothing actually loads and my Genshin models are the same vanilla ones as before.

I am not entirely sure what could be causing this, but I have attempted everything from restarting to reinstalling and there seems to be no high level solution for this problem.

**Comment by leotorrez** [comment]
press f6, f9, or ctrl+alt+f10

those should reload some basic functions

if that dont work try running 3dm as admin

**Comment by JIceberg** [comment]
Nothing I do seems to work for character models. The anti-censorship mod (for the transparency and underwater censorship) I have works just fine, but mods that modify/load on top of character models do not seem to be working at all.

**Comment by JIceberg** [comment]
This problem is still persisting even after a week of uninstalling and reinstalling.
