### ISSUE TITLE
当点击“exports genshin mod folder”时报错

### ISSUE THREAD

**Issue by xiaoyaoqingchun** [SilentNightSound/GI-Model-Importer#23]
我把最新的PlayerCharacterData文件夹下的Ganyu文件夹下的txt文件全部导入至最新版本的blender_2.92软件中（blender已经安装最新的插件），然后没有做任何模型的修改，直接点击导出，但是给我报了一个错误，无法找到"untitledHead.fmt“文件。

**Comment by Modder4869** [comment]
make sure file name matches the folder when you export like Ganyu.vb

**Comment by xiaoyaoqingchun** [comment]
> make sure file name matches the folder when you export like Ganyu.vb

哦，是我给搞忘了，抱歉
