### ISSUE TITLE
CN Server crashes when using more than a certain number of mods

### ISSUE THREAD

**Issue by Fkdxn** [SilentNightSound/GI-Model-Importer#242]
Hello author, this is machine translation. Sorry, after installing a certain number of Mods on the CN server in version 4.4, there will be many crashes. In version 4.6, there will be more crashes. Is there any good way to solve this problem? Mods have been tested and it is normal.
![327031713-d0f6e0c2-3be4-44b2-bf18-97c59b2354d3](https://github.com/SilentNightSound/GI-Model-Importer/assets/146941702/0c15fa4d-9f57-4f5d-90a5-3b7f76f23545)

**Comment by kanonmelodis** [comment]
Same. 
Reducing the number of mods might make things better, but it doesn't necessarily work. 
Restarting the computer will solve the problem temporarily, but over time the problem appears again.

**Comment by leotorrez** [comment]
How many mods is too many xD

**Comment by Fkdxn** [comment]
> 多少个模组才算太多xD
目前精简后留了这么多，看群里有人是10几个G就开始闪退的
![Uploading QQ截图20240503011724.png…]()

**Comment by Fkdxn** [comment]
> How many mods is too many xD

Currently loaded with 24G，There is a probability that this situation will occur if it is over 10G

**Comment by Fkdxn** [comment]
> 相同。减少模组的数量可能会让事情变得更好，但不一定有效。重新启动计算机将暂时解决问题，但随着时间的推移，问题再次出现。

Currently using AGMG's memory startup script

**Comment by leotorrez** [comment]
if you are using over 24 GB of ram with mods then you need smaller mods xD

**Comment by Fkdxn** [comment]
> if you are using over 24 GB of ram with mods then you need smaller mods xD

OK，Thank you very much for your answer，I'll try to streamline the MODS as much as possible first

**Comment by leotorrez** [comment]
Old animation mods were poorly optimized, might be that you have some of those. To fix them you gonna need to do manual editions tho

**Comment by Fkdxn** [comment]
> 旧的动画模组优化得很差，可能是你有一些。要修复它们，您需要进行手动编辑

It's possible that I have installed many animation modules

**Comment by kanonmelodis** [comment]
> Old animation mods were poorly optimized, might be that you have some of those. To fix them you gonna need to do manual editions tho

I don't have any animation mod but still keep crashing. The number or volume of mods I have now is not more than the previous version, but I did not hove similar problems in 4.5....

**Comment by MiyamotoHaruko** [comment]
> 有多少 mod 就太多了 xD

我20G就不行了

**Comment by MiyamotoHaruko** [comment]
> How many mods is too many xD

I have 20G mods, can't run GIMI T_T

**Comment by MiyamotoHaruko** [comment]
I should cut a part of mods and run the GIMI,than repaste this part of mods.

**Comment by MiyamotoHaruko** [comment]
I should cut a part of mods and run the GIMI,then repaste this part of mods.

**Comment by MiyamotoHaruko** [comment]
> > 有多少 mod 就太多了 xD
> 
> 目前加载24G，超过10G就有概率出现这种情况

I cut to 10.1G still can't run GIMI

**Comment by MiyamotoHaruko** [comment]
> > 有多少 mod 就太多了 xD
> 
> 目前加载24G，超过10G就有概率出现这种情况

I cut to less than 10G still can't run it.

**Comment by kanonmelodis** [comment]
> > > 有多少 mod 就太多了 xD
> > 
> > 
> > 目前加载24G，超过10G就有概率出现这种情况
> 
> I cut to less than 10G still can't run it.

The issue may involve some online check in CN client and there's no solution now. You can temporarily solve it by disconnecting network or just rename the mod folder when start the game. There are some related scripts released on #general-CN in AGMG discord server(You can find the server link on GI Gamebanana Page).

**Comment by Fkdxn** [comment]
> > > > 有多少 mod 就太多了 xD
> > > 
> > > 
> > > 目前加载24G，超过10G就有概率出现这种情况
> > 
> > 
> > 我切到不到10G仍然无法运行它。
> 
> 该问题可能涉及CN客户端中的一些在线签入，现在没有解决方案。您可以通过断开网络或在启动游戏时重命名 mod 文件夹来暂时解决它。在 #general-CN的AGMG discord服务器中发布了一些相关脚本（可以在GI Gamebanana页面上找到服务器链接）。

我现在用的就是AGMG的内存启动脚本，断网也可以用，一般都是用的内存启动
