### ISSUE TITLE
The function create_normals_split was removed in Blender 4.1. 

### ISSUE THREAD

**Issue by mykolabernish** [SilentNightSound/GI-Model-Importer#246]
https://developer.blender.org/docs/release_notes/4.1/python_api/#mesh

**Comment by bombless** [comment]
Any workaround available?

**Comment by bombless** [comment]
I removed the call but it now reports another error: `prop "MeshLoop.normal" is read only`

**Comment by SilentNightSound** [comment]
This will be fixed when blender 4.2 LTS comes out; I recommend using blender 3.6 until then. If you really want to use Blender 4.0+, there is an experimental script on the AGMG discord
