### ISSUE TITLE
Mods not going in correctly despite following install instruction

### ISSUE THREAD

**Issue by boiledicecream** [SilentNightSound/GI-Model-Importer#247]
Mods not working correctly in game, mod deformed the character and arent sure how to fix it.

![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/169427361/d0e361c3-90ea-4286-80b9-afd830d64689)

**Comment by 1140s** [comment]
I am having the same issues i have downloaded multiple mods by Hazeker. all I have done is change the key to swich outfits in the merged file. however for some reason only the Ayaka skin works. it is also affecting other skins as well but not consistently and I have turned off dynamic character resolution

Any help would be much appreciated. as I was enjoying trying different skins until this.

1 is Hazekers Ayaka skin working fine and able to switch
2 is Hazekers riden skin not working cant tell if switching same goes for shenhe yelan and jean (all have the same issue)
3 (other creators) bennet skin working fine
4 (other creators) aether skin not working


1
![20240511220240](https://github.com/SilentNightSound/GI-Model-Importer/assets/169561364/65b9068f-7697-4bf5-9cc7-116a2a736451)

2
![20240511220253](https://github.com/SilentNightSound/GI-Model-Importer/assets/169561364/78e034e4-7e2d-4500-9e27-62067dea004e)

3
![20240511220314](https://github.com/SilentNightSound/GI-Model-Importer/assets/169561364/4a35f2d0-1226-475a-9d44-7bbe436480f4)


4
![20240511220107](https://github.com/SilentNightSound/GI-Model-Importer/assets/169561364/a61c887b-8bbe-4263-9c38-8b6b6e1e2c2f)

**Comment by AggroBeat** [comment]
having the same problem.
anyone managed to find a fix?

**Comment by 1140s** [comment]
did some digging and research. this should fix most characters though still quite a few are broken.
https://gamebanana.com/tools/16433. 

Also make sure the dynamic character resolution is turned off likes turning it self on again

**Comment by leotorrez** [comment]
for general mod support head over to discord.gg/agmg

Also avoid posting NSFW Images in these threads
