### ISSUE TITLE
All character mods broken after graphics driver update

### ISSUE THREAD

**Issue by AltoidDev** [SilentNightSound/GI-Model-Importer#251]
After updating my Nvidia graphics drivers to the latest version, all character mods break like in the image, and non-character mods don't work at all.

![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/100539243/255e158a-2ffb-4e24-ba63-0437077a25d1)

**Comment by SilentNightSound** [comment]
Check dynamic character resolution is turned off, it often turns itself back on after gpu driver updates
