### ISSUE TITLE
mods not working?

### ISSUE THREAD

**Issue by ferretbois** [SilentNightSound/GI-Model-Importer#259]
why do my mods not work?
![Screenshot (879)](https://github.com/SilentNightSound/GI-Model-Importer/assets/172452913/8cfbd689-dacd-41e2-8e01-5d20421c3bc0)

i believe i downloaded them correctly. i used this tutorial.

https://youtu.be/H9CeSR9TGlU?si=2pQyw5cmcqSn7ezk

**Comment by leotorrez** [comment]
turn off DCR in graphic config
