### ISSUE TITLE
Blender报错

### ISSUE THREAD

**Issue by hxhxzd** [SilentNightSound/GI-Model-Importer#26]

**Comment by hxhxzd** [comment]
就像这样
![Uploading -4ea086caa021e888.png…]()

**Comment by hxhxzd** [comment]
![-4ea086caa021e888](https://user-images.githubusercontent.com/109600477/180750909-03267778-308c-4d4d-a48a-1f32f7b0ae40.png)

**Comment by hxhxzd** [comment]
我更换了其他模型并重新尝试了，仍然会出现相同的错误。并且已经按照教程重命名了文件名，仍然不行。

**Comment by SilentNightSound** [comment]
确保您使用的是最新的插件，并且您要导出到包含 hash.json 的文件夹

**Comment by xiaoyaoqingchun** [comment]
> 我更换了其他模型并重新尝试了，仍然会出现相同的错误。并且已经按照教程重命名了文件名，仍然不行。

注意以下几点，然后再试试呢：
1、是否把blender软件及其插件更新到最新的版本
2、导出的.vb文件的名称是否与文件夹名称对应，不能是untitled.vb
3、导出到的文件夹里是否有hash.json文件；注意文件名称必须是“hash.json”，不能改成“hash_info.json"

**Comment by hxhxzd** [comment]
问题解决了！十分感谢两位！

**Comment by SilentNightSound** [comment]
Issue was resolved, closing.
