### ISSUE TITLE
Outfits not working at all!! 

### ISSUE THREAD

**Issue by sigduh** [SilentNightSound/GI-Model-Importer#263]
So ive just downloaded two files (only one at a time) for the traveller. 

- https://gamebanana.com/mods/513854
- https://gamebanana.com/mods/489855
 however whenever i load genshin, this happens

. 
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/172902673/f0ab9b54-93de-486f-804d-2dbafdf0c8c4)

**Comment by Kalaborative** [comment]
This is happening for me as well, I tried redownloading the mod and updating to the latest version of 3dMigoto and I'm still getting this weird look.

**Comment by Kalaborative** [comment]
Nvm fixed! You have to go to the settings in Genshin -> Graphics -> Dynamic Character Resolution, make sure it's set to off. Worked for me
