### ISSUE TITLE
GIMI won't load at all. 

### ISSUE THREAD

**Issue by DarkAngel117** [SilentNightSound/GI-Model-Importer#265]
V7, open Loader, states ready to launch game, launch the game through official .exe, game does not start, states that target process found and GIMI loaded successfully but the process dies within a few seconds. Trying to relaunch, closes the loader after process is found and game loads without GIMI. 

Tried both as admin and not as admin. 

![Capture](https://github.com/SilentNightSound/GI-Model-Importer/assets/75085563/3c80a253-9b8c-41e4-9bde-519d1701d3de)

**Comment by yixyming** [comment]
That's the same with my question

**Comment by leotorrez** [comment]
The window is meant to close and the process to die after injection. Check in game to make sure it worked or not by trying to open the help menu.

**Comment by DarkAngel117** [comment]
Figured it out:

By process of eliminating folders from the GIMI directory I narrowed it down to a single .ini file. In that file I narrowed it down to a single command. Apparently using $assignKey breaks the loader somehow and refuses to open the game at all. Replaced value with $autoinfo and it fixed.

**Comment by Victory-zcy** [comment]
> Figured it out:
> 
> By process of eliminating folders from the GIMI directory I narrowed it down to a single .ini file. In that file I narrowed it down to a single command. Apparently using $assignKey breaks the loader somehow and refuses to open the game at all. Replaced value with $autoinfo and it fixed.

I met the same question with you when I tried to load three mods(up to 3GB), when I tried to load any two of them it's ok, but the game process died when I tried to load all the three mods . May I ask which ini file you have modified？I could not find a keyword named "assignKey" in all ini files.

**Comment by DarkAngel117** [comment]
Yeah for sure, it was a mergedmod .ini file named after the mod that was merged. Mod was working fine but inconsistently, I manually changed all of the autoInfo to assignKey tags and process would no longer spawn. Might be a mod specific thing...

**Comment by Victory-zcy** [comment]
> Yeah for sure, it was a mergedmod .ini file named after the mod that was merged. Mod was working fine but inconsistently, I manually changed all of the autoInfo to assignKey tags and process would no longer spawn. Might be a mod specific thing...

Thanks for your help, though I finally didn’t find the file, l learned a lot.

**Comment by leotorrez** [comment]
> Figured it out:
> 
> By process of eliminating folders from the GIMI directory I narrowed it down to a single .ini file. In that file I narrowed it down to a single command. Apparently using $assignKey breaks the loader somehow and refuses to open the game at all. Replaced value with $autoinfo and it fixed.

care to show a sample of the ini file in question? This sounds like a big issue

**Comment by DarkAngel117** [comment]
Sure! Here is the offending .ini file (in txt format). Hilarious thing just happened when I tested it again, the game booted. Not sure what changed. I havent opened the game for 2 weeks at this point so maybe a phantom update or something? Will see if it continues to work or not. Did not change anything else. 

[merged.txt](https://github.com/user-attachments/files/16114572/merged.txt)

**Comment by leotorrez** [comment]
This bug will be fixed in a future dll release
