### ISSUE TITLE
Issue with the Arlecchino mod 

### ISSUE THREAD

**Issue by olik13-ux** [SilentNightSound/GI-Model-Importer#267]
Mods doesn't seem to be applying to the character only the original mod is applying.
![Screenshot 2024-06-28 112659](https://github.com/SilentNightSound/GI-Model-Importer/assets/174086471/2229b37c-91c7-4677-a874-6678a4ce5990)

**Comment by leotorrez** [comment]
for general mod support head over to discord.gg/agmg
