### ISSUE TITLE
Dumps not Collecting All Textures

### ISSUE THREAD

**Issue by TechnoSchnauzer** [SilentNightSound/GI-Model-Importer#268]
I was trying to dump this object: 
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/108784157/a58e43e3-6a6c-46c6-8293-3d15eb816ebd)
And while it did dump I noticed that there was no texture for the large bulb ontop.
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/108784157/cd0f6739-5303-46f7-ab24-b5008baca247)
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/108784157/d9587e54-e5f0-4897-acfa-9ed70db160e6)
Looking at it's uvs I saw where they were placed and did a dump using every PS hash that had any effect on the object, and still didn't get a texture that fit it. After that I did a dump of everything and there was still no texture of it.
Looking back at how I've not had normal maps dump when there seemed to be a normal map on the object, or no lightmap dumping I think there may be a problem happening.
May it be an issue on my side or is it a code issue?

**Comment by leotorrez** [comment]
the collect script is only intended to be used on characters. weapons and objects are not supported, yet it might happen to work. For objects like this use manual collecting

**Comment by TechnoSchnauzer** [comment]
I didn't realize I didn't mention it, but I was manually collecting. The texture was not at all showing up in the frame dump folder. I wasn't using the collecting script.

> the collect script is only intended to be used on characters. weapons and objects are not supported, yet it might happen to work. For objects like this use manual collecting

**Comment by leotorrez** [comment]
oh I see, in which case you might have to check the framedumps in greater detail. Check the render targets to see when this object gets drawn and note down the IB used to draw it. Then check where else that IB is used in a PS call. The other calls related to that mesh will be easy to track this way. The texture could be applied after the initial draw of the mesh

**Comment by TechnoSchnauzer** [comment]
Could you give me a bit more direction?
I'm fairly sure I did what you asked and still didn't find it, but want to make sure I did it right.

**Comment by leotorrez** [comment]
contact me in discord.gg/agmg if possible. If you can't the alternative is to check log file in the framedump folder for the hashes related to the mesh you are trying to mod and check all the calls related to them and the textures used in each of them. Some has to be the ones you need
