### ISSUE TITLE
My Character need to drink milk 

### ISSUE THREAD

**Issue by mustafa255kw** [SilentNightSound/GI-Model-Importer#271]
![image_2024-07-04_025045717](https://github.com/SilentNightSound/GI-Model-Importer/assets/174663385/d397e6af-d0f9-443c-8cb8-0d99dbf714b4)

**Comment by leotorrez** [comment]
I advice cocogoat milk. Or turning off dcr- For general modding support please head over to discord.gg/agmg help channels. These issues threads are for issues related with the tool not the mods made with it.
