### ISSUE TITLE
Weapons look Unascended after Blender Export

### ISSUE THREAD

**Issue by CorvidArekusu** [SilentNightSound/GI-Model-Importer#272]
As the title says, I tried replacing a weapon with another one, and after everything was done and I loaded the mod, the modded model looks like before Ascension 2, even though the weapon I'm replacing is Level 90. How to fix this?

**Comment by CorvidArekusu** [comment]
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/112361234/021f2b02-7f5a-42a0-a5a0-872fbae46a8e) Normal Weapon (lvl90)

![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/112361234/1adea82f-7013-47f3-9d9c-25170172287a) Modded Weapon (lvl90)

**Comment by leotorrez** [comment]
3dm is working as intended in this case. Mod issues are better addressed at discord.gg/agmg help channels.

Your issue is likely due the initial dump being made when the weapon was low level. Make a new dump using lvl 90 wep
