### ISSUE TITLE
Can't work with FPS unlock function 不能和帧率解锁的功能一起使用

### ISSUE THREAD

**Issue by hoshiizumiya** [SilentNightSound/GI-Model-Importer#276]
# Have someone encountered this problem? I have tried to check out the reasons:
1. Both programs use like “Inject codes at startup”. It may try to rewrite the same address in the program but they made conflict.
2. FPS unlock program seem to will restart GenshenImpact.exe after it work, but the mod program only work once and exit.
## 有人遇到这个问题吗？我试着找出原因：
1. 这两个程序都使用类似于“启动时注入代码”的方法。它可能试图重写程序中的相同地址，但它们产生了冲突。
2. FPS解锁程序工作后似乎会重新启动GenshenImpact.exe，但mod程序只工作一次就退出了。

**Comment by 3058132083** [comment]
刚试了下，关闭解除锁帧之后好了

**Comment by SilentNightSound** [comment]
The programs should work together as far as I know - run GIMI first followed by FPS unlock

**Comment by Griffures** [comment]
Can confirm, Running both. Gimi, Reshade injector, then unlocker that auto start genshin.
All 3 inject themselves.
