### ISSUE TITLE
Tips to start `3DMigotoLoader.exe` on M-series Mac

### ISSUE THREAD

**Issue by whq-hqw** [SilentNightSound/GI-Model-Importer#277]
## 中文
我使用 [crossover 24.04](https://www.codeweavers.com/crossover)在M3 Mac上跑起了原神4.7版本。之后想尝试`3DMigotoLoader.exe`来加载MOD，但是在CrossOver安装时出现如下错误:
```
3DMigoto version size check failed
```
我感觉像是因为路径没有设置好导致的问题，因此做了一下的尝试：
- 将`d3dx.ini`中的`target = GenshinImpact.exe`替换成Mac中的原神安装路径：`\Users\MY_USER_NAME\Library\Application Support\CrossOver\Bottles\Genshin Impact\drive_c\Program Files\HoYoPlay\games\Genshin Impact game\GenshinImpact.exe`
- 尝试不同的斜杠，mac版本的 `/` 和Windows版本的 `\`，都出现同样的错误

## English 
I'm use [crossover 24.04](https://www.codeweavers.com/crossover) to run the latest 4.7 genshin impact without a problem.
So I tried to install `3DMigotoLoader.exe` as well, during the installation, it gave the following error:
```
3DMigoto version size check failed
```
I assume this might be cause due to the genshin installation path is different on Windows, so I did the following things: 
- Replace `target = GenshinImpact.exe` in `d3dx.ini` with the path genshin installed. In my case it was `\Users\MY_USER_NAME\Library\Application Support\CrossOver\Bottles\Genshin Impact\drive_c\Program Files\HoYoPlay\games\Genshin Impact game\GenshinImpact.exe`
- For the above path I tried using normal `/` and windows' `\`, both result to the same error.

**Comment by SilentNightSound** [comment]
3dmigoto/GIMI was designed for windows, not sure if it works on Mac at all - there is a guide to get it functional on Linux in AGMG, but I believe Mac has a second translation layer between its GPU drivers and d3d11 (compared to Linux with 1 and Windows with 0) so it may not be functional

**Comment by whq-hqw** [comment]
Thanks for the answer, it seems to be pretty difficult to make it work, I'll close the issue for now.
