### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by Ennnnnnnnnnnnnnnn** [SilentNightSound/GI-Model-Importer#279]
my kaeya model isnt loading in correctly but all my other mods still work normally. im still relatively new to modding but all my other mods so far has been operational, except this mod
![Screenshot (4)](https://github.com/user-attachments/assets/c2d32cee-1328-4f02-a8f5-a7e2032f6816)
![Screenshot (5)](https://github.com/user-attachments/assets/fa39bac6-be97-42cd-8cf1-e5f1173f025e)
![Screenshot 2024-07-19 020755](https://github.com/user-attachments/assets/f7b44789-3edc-498e-9d00-49285306f246)

**Comment by Ennnnnnnnnnnnnnnn** [comment]
nvm i got it fixed

**Comment by 4nyNoob** [comment]
> nvm i got it fixed

how did you fix it?
