### ISSUE TITLE
把一个角色身体一部分替换到另一个角色身上时,游戏内模型错乱

### ISSUE THREAD

**Issue by yejunjie10311031** [SilentNightSound/GI-Model-Importer#28]
我把一个角色身体的一部分复制到另一个角色身上,并且缝合得很完美,在blender里看很正常,但当我在游戏中加载它时,模型却是错乱的。
![屏幕截图 2022-07-27 150802](https://user-images.githubusercontent.com/62139629/181187237-eadb9b1c-aebc-4183-af5c-8aa4100f2ad5.jpg)
![Genshin Impact 2022_7_27 15_10_56](https://user-images.githubusercontent.com/62139629/181187251-9a24ccba-c16b-484a-9547-a66dcd2e0c9e.png)

**Comment by yejunjie10311031** [comment]
我当时的步骤是这样的：我把万叶的上半身删去,然后把刻晴的上半身和dress复制过来,并且把它和万叶的下半身缝合好,blender里看上去没问题,但在游戏里模型是错乱的。

**Comment by iris10086** [comment]
没改权重。

**Comment by yejunjie10311031** [comment]
> 没改权重。

我尝试把万叶或刻晴的权重传递给我当前的模型,但在游戏中模型仍然是错乱的

**Comment by yejunjie10311031** [comment]
@iris10086 已经解决了,谢谢。

**Comment by yejunjie10311031** [comment]
> > 没改权重。
> 
> 我尝试把万叶或刻晴的权重传递给我当前的模型,但在游戏中模型仍然是错乱的

我把总共101个顶点组的权重全传递了一遍,现在游戏内也显示正常了,昨天只传了一个顶点组的权重（因为不熟悉操作）

**Comment by yejunjie10311031** [comment]
问题已解决
