### ISSUE TITLE
Loader gets Blocked by Anti Cheat

### ISSUE THREAD

**Issue by Mangaclub** [SilentNightSound/GI-Model-Importer#280]
Every time i start the Game (yesterday it was fine) i get a message of Anticheat.
Seems Genshin intoduced somethign new?
also the d3d11 file gets either Deleted or Rnamed to something like: d3d11.dll.4293317268

[d3d11_log.txt](https://github.com/user-attachments/files/16336373/d3d11_log.txt)
![VMsggMJKpW](https://github.com/user-attachments/assets/c9aca6a8-7faf-4d67-976f-28f0e395a2f3)

**Comment by SilentNightSound** [comment]
Don't put GIMI in the game folder, run it from any other folder. If you run it in the game folder it will occasionally trigger anticheat

**Comment by Mangaclub** [comment]
OHHHHH okayyyy i didnt see that on the install notes, thanks! Works now
