### ISSUE TITLE
The file opened, but there was no response after starting the game. Please help me, thank you.

### ISSUE THREAD

**Issue by xianguyong** [SilentNightSound/GI-Model-Importer#282]
Hello, I am in the China region and it has been unresponsive when I try to open it recently. There is no problem with starting it up, but when I try to open the game itself, there is no response. I hope to get your help. Thank you.

**Comment by xianguyong** [comment]
3dmigoto starts normally, but when starting the game, it seems that Genshin cannot be read because I don't quite understand it. I hope to get your assistance.

**Comment by xianguyong** [comment]
3dmigoto starts normally, but when starting the game, it seems that Genshin cannot be read because I don't quite understand it. I hope to get your assistance.

**Comment by xianguyong** [comment]
Is the Chinese version of the game launcher called yuanshen.exe different from the international version?

**Comment by xianguyong** [comment]
Hello, my issue has been resolved. I replaced Genshin with yuanshen in the file, cleared all mods, and restarted the game launcher and 3dmigoto. It was successful. thank.

**Comment by Anistorica** [comment]
replace Genshin in the ini foder called "d3dx.ini" into Yuanshin or the laucher wasnt able to find the very laucher
