### ISSUE TITLE
Problem with Emilies flowers

### ISSUE THREAD

**Issue by rxsequortz** [SilentNightSound/GI-Model-Importer#290]
Hi do you know to fix this mod? Basically the flowers on top of Emilies lantern is supposed to stay purple after the burst animation but they turn back to green

https://github.com/user-attachments/assets/79f4ce62-f6fa-48b0-8f89-b804cf71c0cf

**Comment by rxsequortz** [comment]
Do you how to make it stay purple?

**Comment by leotorrez** [comment]
Solidify or similar. For mod making help head to discord.gg/agmg this thread is to fix problems with the mod injection tool
