### ISSUE TITLE
3dmigoto wont work

### ISSUE THREAD

**Issue by cubyology** [SilentNightSound/GI-Model-Importer#291]
this didnt use to happen before. every time i launch the 3dmigoto loader and then genshin through the launcher it says "Checking if 3dmigoto GIMI was successfully loaded : 299" after that, before it broke, it used to count until 5 and then launch the game with zero issues. now, there is no countdown and when the game launches, 3dmigoto doesnt work. the loud buzz sound doesnt play either. i've tried uninstalling and reinstalling 3dmigoto multiple times and every time it's the same. if i'm lucky, i get it to launch correctly once and then never again.

**Comment by AlbertoParedesRivas** [comment]
I had this, for some reason GIMI is taking way too much time to start, i fixed it by opening the `d3dx.ini` file with notepad and searching for this block of text
```
; Delay this many extra seconds after confirming that 3DMigoto was loaded in
; the target process. For games that respawn themselves or have multiple
; executables of the same name when the first process we see may not be the
; actual one we need. Set to -1 to disable automatic shut down.
;delay = 20
```
Removing the ; on the delay line and restarting the game made GIMI work again. Hope it helps

**Comment by cubyology** [comment]
oh, thank you so much! this actually helped! i can finally play with my mods again :D
