### ISSUE TITLE
Genshin mods completely broken as of 4.8 Emilie release patch, please help :')

### ISSUE THREAD

**Issue by skullyadris** [SilentNightSound/GI-Model-Importer#293]
Everything was working fine until Emilie's release update. Sigewinne's patch was fine, and everything before that was fine. As per usual, there were new patches in the past, and multiple people had issues with mods breaking, but they were promptly fixed by modders on gamebanana in a timely manner; but this time, nothing. I'm the only one having the issue, to my knowledge. It's the same kind of issue where everything that's modded is a jumbled mess of polygons and textures, but nothing I do fixes it.
I also downloaded a few mods that were just released a day or two ago. They are also broken, so I know that the issue is on my end somewhere.
Would really appreciate some help here, I hate not being able to play with my mods :(((

**Comment by adonite** [comment]
Also having this issue, I just downloaded GIMI for the first time yesterday as well, so I have no idea what problem could exist here on my end. Every model I try ends up looking like stretched polygons, not dissimilar to the example of mismatched IB and VB in the troubleshooting guide, even one that was uploaded today. I can't imagine every single model has that though, and I also notice that in the character menu if I look at the reflection of the garbled model in the floor the mod model is intact ONLY in the reflection. Tried to see if I'm just screwing up adding the mods somehow, but as far as I can tell, that is not the case.
![Untitled](https://github.com/user-attachments/assets/ba616411-8b2c-411e-a09b-2f276919e8c6)

**Comment by JACOBnotpro** [comment]
me have the same issue. Before Emilie's release update, I used to play game with 1 hand. Now I must use 2 of them. Hope that this problem will be fixed soon 😭
Thanks alot for your work!!

**Comment by AlbertoParedesRivas** [comment]
I had this, turns out `Dynamic Character Resolution` turned on automatically, shut it off and F10 fixed all my mods.

**Comment by adonite** [comment]
> I had this, turns out `Dynamic Character Resolution` in Graphics Settings turned on automatically, shut it off and F10 fixed all my mods.

this fixed everything, good tip.

**Comment by skullyadris** [comment]
> I had this, turns out `Dynamic Character Resolution` in Graphics Settings turned on automatically, shut it off and F10 fixed all my mods.

oh my god, I would've never thought it'd turn back on!! thank you so much, everything's fixed <3

**Comment by skullyadris** [comment]
> Also having this issue, I just downloaded GIMI for the first time yesterday as well, so I have no idea what problem could exist here on my end. Every model I try ends up looking like stretched polygons, not dissimilar to the example of mismatched IB and VB in the troubleshooting guide, even one that was uploaded today. I can't imagine every single model has that though, and I also notice that in the character menu if I look at the reflection of the garbled model in the floor the mod model is intact ONLY in the reflection. Tried to see if I'm just screwing up adding the mods somehow, but as far as I can tell, that is not the case. ![Untitled](https://private-user-images.githubusercontent.com/178749843/358952167-ba616411-8b2c-411e-a09b-2f276919e8c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzgwMzEsIm5iZiI6MTcyNDEzNzczMSwicGF0aCI6Ii8xNzg3NDk4NDMvMzU4OTUyMTY3LWJhNjE2NDExLThiMmMtNDExZS1hMDliLTJmMjc2OTE5ZThjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwNzA4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2U1NTM0MTExYWExZGY4NmJiMTAyZmI1ZGU4YTJjYjE3NGU2ODI3MmUzOTg2Y2NjNTU0MTg3MzliMGFiNmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r2n_wXsswmWUPvB4tq3EveUnJpa_9UegjShJhxed0T4)

apparently it's because the dynamic character resolution gets automatically turned on after new updates sometimes! thanks to one of the commenters here for pointing it out :')

**Comment by skullyadris** [comment]
> me have the same issue. Before Emilie's release update, I used to play game with 1 hand. Now I must use 2 of them. Hope that this problem will be fixed soon 😭 Thanks alot for your work!!

apparently it's because the dynamic character resolution gets automatically turned on after new updates sometimes! thanks to one of the commenters here for pointing it out :')

**Comment by JACOBnotpro** [comment]
> I had this, turns out `Dynamic Character Resolution` in Graphics Settings turned on automatically, shut it off and F10 fixed all my mods.

It's not working 
![Screenshot (653)](https://github.com/user-attachments/assets/8996ed76-d97e-4bc0-97b3-f859098113a1)
![Screenshot (652)](https://github.com/user-attachments/assets/59ae0070-135b-4120-864d-fcf36333910a)
![Screenshot (651)](https://github.com/user-attachments/assets/c842f367-97da-4694-b1ea-61047e10a836)
*already f10 to reload the mod -> nothing happen 😭

**Comment by bocai1978** [comment]
> > I had this, turns out `Dynamic Character Resolution` in Graphics Settings turned on automatically, shut it off and F10 fixed all my mods.
> 
> It's not working ![Screenshot (653)](https://private-user-images.githubusercontent.com/128392714/360455297-8996ed76-d97e-4bc0-97b3-f859098113a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDAxMTgsIm5iZiI6MTcyNTE5OTgxOCwicGF0aCI6Ii8xMjgzOTI3MTQvMzYwNDU1Mjk3LTg5OTZlZDc2LWQ5N2UtNGJjMC05N2IzLWY4NTkwOTgxMTNhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQxNDEwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGMzNjI4MGUwNTk5NjNmZjFmMjQ1ZjY4N2RmNDNiZWYwZTE3ODI3MTc5YmI5ZTY2YmE4ZjNiOTc5MTQ2MzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E_PjAs9wmDvri5Uo4FbY0RBdLVf5R1gQMCzk3W7bdB0) ![Screenshot (652)](https://private-user-images.githubusercontent.com/128392714/360455320-59ae0070-135b-4120-864d-fcf36333910a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDAxMTgsIm5iZiI6MTcyNTE5OTgxOCwicGF0aCI6Ii8xMjgzOTI3MTQvMzYwNDU1MzIwLTU5YWUwMDcwLTEzNWItNDEyMC04NjRkLWZjZjM2MzMzOTEwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQxNDEwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDliY2UxZGJlMjg0N2U3NTIwMDU2MDc0YTM5ZTNlYjZlNjUzY2M3MjVjYmU4NTYwYWY5MjM4NDMxYTkzYmYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dp-3ztWUQtlhkq0T-5vil6Msxfn9kyoOCtKf4XDn5l0) ![Screenshot (651)](https://private-user-images.githubusercontent.com/128392714/360455342-c842f367-97da-4694-b1ea-61047e10a836.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDAxMTgsIm5iZiI6MTcyNTE5OTgxOCwicGF0aCI6Ii8xMjgzOTI3MTQvMzYwNDU1MzQyLWM4NDJmMzY3LTk3ZGEtNDY5NC1iMWVhLTYxMDQ3ZTEwYTgzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQxNDEwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWVkNjg3ODk2ZmNhNGE1M2M3N2M5NjMxOTA1ODQzNjNkMGFkNTFjMmU2NjIyY2JhOTMzYmRiOGJkM2MxNGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DmROCUqw40Y4CE5qXlzp_bASsDqmu2prBrd_j54rHTQ) *already f10 to reload the mod -> nothing happen 😭

give u a url:  https://gamebanana.com/tools/16433

**Comment by bocai1978** [comment]
> > I had this, turns out `Dynamic Character Resolution` in Graphics Settings turned on automatically, shut it off and F10 fixed all my mods.
> 
> It's not working !
> *already f10 to reload the mod -> nothing happen 😭

give u a url: https://gamebanana.com/tools/16433

**Comment by leotorrez** [comment]
solved issue
