### ISSUE TITLE
There will be an error when the mod is turned on.

### ISSUE THREAD

**Issue by wppkkr** [SilentNightSound/GI-Model-Importer#296]
Mod manager website ：https://d3dxskinmanage.numlinka.com
Here is screenshot ，how can I fix this? （这是问题截图 我要怎样解决这个问题）
![QQ20240820-164554](https://github.com/user-attachments/assets/e24f81fa-bbc2-44b8-ba20-90bc3a8e1222)

**Comment by leotorrez** [comment]
We don't provide mod use support. This is just for mod injection tool. Use discord.gg/agmg for help
