### ISSUE TITLE
导出时Blender报错

### ISSUE THREAD

**Issue by Xinshou233** [SilentNightSound/GI-Model-Importer#30]
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blender_3dmigoto_gimi.py", line 2121, in execute
    export_3dmigoto_genshin(self, context, object_name, vb_path, ib_path, fmt_path, self.use_original_tangents)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blender_3dmigoto_gimi.py", line 1267, in export_3dmigoto_genshin
    stride = obj['3DMigoto:VBStride']
KeyError: 'bpy_struct[key]: key "3DMigoto:VBStride" not found'
2.92，3.2都会出现这样的问题

**Comment by SilentNightSound** [comment]
确保从原始 3dmigoto 对象转移自定义属性 (https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Tools/custom_property_transfer_script.txt)

![image](https://user-images.githubusercontent.com/107697535/182503287-60cbcb88-1b91-4ff8-85fa-273df29f35a7.png)

**Comment by Xinshou233** [comment]
ModuleNotFoundError: No module named 'bpy'是怎么回事

**Comment by Xinshou233** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\utao.blend\Text", line 14, in <module>
KeyError: 'bpy_prop_collection[key]: key "transfer_from" not found'
这是怎么回事qwq

**Comment by SilentNightSound** [comment]
将“transfer_to”和“transfer_from”更改为您想要将属性传入和传出的对象

**Comment by SilentNightSound** [comment]
Question was answered, no further activity in the last month. Closing issue.
