### ISSUE TITLE
characters inside-out

### ISSUE THREAD

**Issue by ysuriofficiel** [SilentNightSound/GI-Model-Importer#307]
I don't have any mods for these characters, but they are all inside out and make my game crash as soon as they are on screen, I managed to get some screen for them, but not all so here's the list: Mualani, Kinich, Kachina, XIanling, Bennet, Gaming, Kuki Shinobu, Heizou, Fischl (when using her normal skin, the paid one in the shop works fine), 
![Capture d'écran 2024-09-18 024556](https://github.com/user-attachments/assets/2b7d8a51-af8e-4449-8517-c04e9e16dbc1)
![Capture d'écran 2024-09-18 024624](https://github.com/user-attachments/assets/ece6b688-9ca0-4996-888b-f5b8d3f2648b)
![Capture d'écran 2024-09-18 024637](https://github.com/user-attachments/assets/b0b5d1eb-ec25-47f1-9e63-7ece5cff95d4)
![Capture d'écran 2024-09-18 024648](https://github.com/user-attachments/assets/8dfb961c-4ac2-425d-9515-048f4efbe22e)
![Capture d'écran 2024-09-18 024706](https://github.com/user-attachments/assets/d1be5125-b1c1-4777-ac68-27057af187ec)

Edit: I checked with a friend, and He doesn't have this problem for any character, so I know it's on my side now but I've tried everything I could think of, but none worked, I reinstalled genshin, I reinstalled 3Dmigoto, I tested with no skins at all, I tested putting skins on the characters concerned in hope it would fix it but nope.

**Comment by leotorrez** [comment]
Texfx bug. And a known issue. Wait for update on it and check their repo. Unrelated with thus repository
