### ISSUE TITLE
toggles not working

### ISSUE THREAD

**Issue by hetsuhetsu** [SilentNightSound/GI-Model-Importer#311]
im using this: https://gamebanana.com/mods/535653 (yelan mega mod)

the toggles tell me to use ] and [ , but they are not working for me. the mod itself loads normally, but i cant change the outfit.
Im using the newest GIMI version, and have many other mods installed where i dont have any issues with toggles.

Does anyone have any idea what might cause this issue? thank you in advance :)

**Comment by leotorrez** [comment]
This is not a channel to ask for mod support. Try discord.gg/agmg for that kinda help, they have the pertinent channels to deal with this kind of things.

As for your issue, is likely just a case of your keyboard config. Change the ini so the key is a different one instead
