### ISSUE TITLE
3Dmigoto loader is broken for me

### ISSUE THREAD

**Issue by hypersplatoonist** [SilentNightSound/GI-Model-Importer#312]
after installing the gimi for playing mods, and trying to launch 3Dmigoto loader, it gives me two error messages. 
the first reads as following: the code execution cannot procced because VCRUNTIME140.dll was not found. reinstalling the program may fix this problem.
the second reads as following: the code execution cannot procced because MSVCP140.dll was not found. reinstalling the program may fix this problem.
reinstalling the program infact did not fix the problem. i dont understand why it doesent work. i played genshin on a different laptop before and ive never encountered this issue before but ive got a new laptop so i wanted to play the game on it. the issue might be caused by how old and already used my new laptop is but i dont think thats the reason. if anyone could help i would be super duper grateful.

**Comment by leotorrez** [comment]
x86: https://aka.ms/vs/17/release/VC_redist.x86.exe

x64: https://aka.ms/vs/17/release/VC_redist.x64.exe

These should fix your issue

**Comment by hypersplatoonist** [comment]
YES TYSMM
