### ISSUE TITLE
3dmigoto collect error

### ISSUE THREAD

**Issue by henrietta2243** [SilentNightSound/GI-Model-Importer#313]
When trying to dump model i got error 

Searching for VB corresponding with root vS
(most recent call last):
File "D: \3DMigotoDev\genshin_3dmigoto_collect.py", line 708, in ‹module> main®
File
line 58, in main
relevant ids, first_vss
IndexError: list index out of range

There are no mods in mods folder and using new extracted files also give me same error

**Comment by RoxyRead** [comment]
Hey, how did you end up fixing this? I am having the same problem.

**Comment by leotorrez** [comment]
We no longer use this tool to collect dumps. Gui collect from petrascyl is the new tool
