### ISSUE TITLE
使用3dm加载mod出现错误，command list recursion limit exceeded  circular reference一直刷屏没有消失

### ISSUE THREAD

**Issue by wdawddagf** [SilentNightSound/GI-Model-Importer#316]
command list recursion limit exceeded  circular reference我在加载原神人物模型时出现了这样的问题怎么办
![1](https://github.com/user-attachments/assets/3d0b2ddd-c48b-4a6b-a2c1-3b26db4b507d)

**Comment by leotorrez** [comment]
some of your inis is doing loops in a silly way. Turn them off in batches till you find culprit. Then bring the ini here so we can analyse it
