### ISSUE TITLE
model not working properly

### ISSUE THREAD

**Issue by fishf-x** [SilentNightSound/GI-Model-Importer#322]
I'm not entirely sure whats wrong with it but i've tried doing everything the help menu and troubleshooting told me to and it still looks like this
![20241113154041](https://github.com/user-attachments/assets/c43602ad-86a4-4fcc-9215-2397a86f2382)

**Comment by leotorrez** [comment]
did you turn DCR off in graphic settings?

**Comment by fishf-x** [comment]
oh! that did work thank you
