### ISSUE TITLE
Mods won't load but 3migoto launches successfully?

### ISSUE THREAD

**Issue by dippsta** [SilentNightSound/GI-Model-Importer#324]
The black bat screen says the game location is found and mods have been loaded but when the game starts it doesn't show that it's loaded (usually hear 2 beeps but not anymore), and when I enter my account no mods are loaded. 

This started recently is this a 5.2 issue? I tried changing the path got the game in the d3dx.ini and nothing, tried reinstalling genshin, 3migoto, and skinselectimpact, nothing. Tried opening through the Hoyo launcher and the direct from the GenshinImpact.exe nothing. 

Weirdly it worked 2 days ago all the sudden by opening it directly with the GenshinImpact.ece, but now it's back to not working.

**Comment by leotorrez** [comment]
the latest hoyo launcher install might have installed your game into a differnt location than your usual. check the path in its configurations

**Comment by dippsta** [comment]
The path is still in the same configurations and it doesn't work :/

**Comment by dippsta** [comment]
Aaaaand it's not working AGAIN 😭 I'm at a loss at this point

**Comment by dippsta** [comment]
Nvm, I stopped playing for a bit and now it's doing the same thing again. Goodbye modded genshin i guess
