### ISSUE TITLE
Windows 10 IME suggestion list cannot be displayed, when using the Microsoft Pinyin IME(Chinese) with GIMI running.

### ISSUE THREAD

**Issue by hfxu** [SilentNightSound/GI-Model-Importer#35]
Hi 
I found that Windows 10 IME suggestion list(Chinese) is blank when using in-game chat via GIMI running.

1. With GIMI running, the IME suggestion list is blank: 
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/8024147/191288373-17bc436a-8091-4a3b-9dad-5eddbd3d825e.png">

2. Without GIMI run, the IME suggestion list works well:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/8024147/191290843-4f05307b-95a3-426e-8724-a7b69f4be33d.png">

I'm not sure this is a reproducible issue, and is it possible to be fixed in future? Thank you.

**Comment by SilentNightSound** [comment]
I don't seem to be able to reproduce the issue - it is still happening?
