### ISSUE TITLE
已正确配置游戏路径，3DMigoto Loader.exe莫名闪退

### ISSUE THREAD

**Issue by zhinian178** [SilentNightSound/GI-Model-Importer#37]
在输出几句如图中所示语句后，程序闪退
![image](https://user-images.githubusercontent.com/63533151/193440302-f3634169-601b-4ad1-855e-5a1320dbbd41.png)

**Comment by wang089** [comment]
就是这样

**Comment by SilentNightSound** [comment]
The program is intended to close after it finishes injecting. Closing ticket.

**Comment by asqkl1** [comment]
我也这样有什么解决方法么，查遍了都没这一点的说明
