### ISSUE TITLE
failed to load custom textures

### ISSUE THREAD

**Issue by CYNKM** [SilentNightSound/GI-Model-Importer#39]
![problem](https://user-images.githubusercontent.com/115446225/196421476-4c2d8c7d-75bd-45dd-a458-04c1e6cdb9e8.PNG)

i'm not sure why this happens, but my guess is on the ini file and the match_first_index = 0 might be causing it, is there a fix for this?

**Comment by SilentNightSound** [comment]
Hmm, it is hard to tell from this alone. If you are using Linux, I know it has some issues loading the shadowramp file - I would recommend deleting those lines in the ini. 

Very few mods (none I think?) currently modify the shadowramp so you can safely delete it without causing issues.

**Comment by CYNKM** [comment]
i'm using windows but deleting the lines in the ini file worked, thanks for the help

**Comment by SilentNightSound** [comment]
glad to hear it is working!
