### ISSUE TITLE
可否根据血量变化来切换模组

### ISSUE THREAD

**Issue by fangwenpolar** [SilentNightSound/GI-Model-Importer#41]
有一个想法，希望能实现根据血量变化来切换mod,血量变少则自动切换到衣服少的mod。有个简单的构想是获取血条上某像素点的颜色，然后根据红、绿判断来切到对应mod，效果有点像战斗中爆衣。一个突发奇想，跟大大分享一下

**Comment by SilentNightSound** [comment]
谢谢你的主意！我实际上是在努力让它发挥作用，有几个问题让它变得棘手。希望它能尽快发布
