### ISSUE TITLE
Is it possible that merged mods switch only the current character?

### ISSUE THREAD

**Issue by jianxingxuejian** [SilentNightSound/GI-Model-Importer#42]
Now all characters using the same key will be switched together. Can you provide an option to control whether to switch together or not?

**Comment by SilentNightSound** [comment]
There isn't any way that I know of to have the key only switch some characters or not others if they use the same one. It is possible to change what key characters use by modifying the merged.ini though, which is an alternative. I'll look into better solutions

**Comment by SilentNightSound** [comment]
Feature has now been added to the merge mod script.
