### ISSUE TITLE
problem with favonius sword mod

### ISSUE THREAD

**Issue by thong997** [SilentNightSound/GI-Model-Importer#43]
![Screenshot_20221202_075606](https://user-images.githubusercontent.com/42855513/205300878-b076b8b3-1f21-46d2-9c79-440fd82d1e6f.png)

**Comment by SilentNightSound** [comment]
Usually this is because of a mismatch between the vb and ib files (either because the export was broken, or because you are using multiple mods for that weapon/model)

**Comment by f865njhjlj** [comment]
and how can i fix it

**Comment by leotorrez** [comment]
update hashes. the new ones are in the assets repo
