### ISSUE TITLE
When can I modify the face?

### ISSUE THREAD

**Issue by wang089** [SilentNightSound/GI-Model-Importer#49]
When can I modify the face?

**Comment by sllvee** [comment]
你可以提取脸模修改或删掉，修改脸模会有问题，原神的脸模是许多角色共用的，你修改一个 可能其它角色的脸也会被修改

**Comment by wang089** [comment]
> 你可以提取脸模修改或删掉，修改脸模会有问题，原神的脸模是许多角色共用的，你修改一个 可能其它角色的脸也会被修改

有教程吗，我不会qwq

**Comment by sllvee** [comment]
要啥教程，会提取模型和做mod就行了，脸模有问题不建议修改。这俩都不会当我没说    b站有教程

**Comment by wang089** [comment]
> 要啥教程，会提取模型和做mod就行了，脸模有问题不建议修改。这俩都不会当我没说 b站有教程

6
