### ISSUE TITLE
NilouMod bugs

### ISSUE THREAD

**Issue by Quinella1516** [SilentNightSound/GI-Model-Importer#51]
mod download link:https://gamebanana.com/mods/418608
Nilou charactor model broke after I use mod above with 3Dmigoto

**Comment by SilentNightSound** [comment]
Hello. Usually restarting the game will fix most issues, but if it doesn't try downloading a fresh version of the program from this repository.

**Comment by SilentNightSound** [comment]
No update in several weeks, closing ticket
