### ISSUE TITLE
Another instance open bug?

### ISSUE THREAD

**Issue by RaveXD** [SilentNightSound/GI-Model-Importer#52]
![image](https://user-images.githubusercontent.com/121534581/209758368-ac7c8e80-0727-42b7-8cda-79ab5650b5e6.png)

Even after restarting my computer, this pops up, this is also my first time modding, and not sure how to fix it, please help.

**Comment by RaveXD** [comment]
My discord is Rave#7931

**Comment by Chipotleguest** [comment]
Did you ever figure out the problem?

**Comment by kmacd92** [comment]
Also having the same issue. Restarting and fully shut down my machine yet despite this the error still appears upon opening the program. From checking Task manager while all instance of the Window are closed the error still appears on starting the program

**Comment by kmacd92** [comment]
And right as I post I figure it out. Go into the Properties for the exe and set it to Run as Admin. This fixes the issue

**Comment by SilentNightSound** [comment]
Issue resolved, closing ticket
