### ISSUE TITLE
Is it possible to share how the mechanism works?

### ISSUE THREAD

**Issue by KiyoshiMu** [SilentNightSound/GI-Model-Importer#53]
Hello, first thanks for making & sharing of this amazing tool!

I'm trying to understand how the **model swap feature** of this software works, but I'm having trouble figuring it out. And Google doesn't help. Could you provide some more information or documentation on its underlying mechanism? Thank you!

**Comment by SilentNightSound** [comment]
Hello! For learning how to mod, there are several tutorials on [gamebanana](https://gamebanana.com/tuts/games/8552). If you are more interested in the underlying mechanics of how 3dmigoto functions, there isn't too much documentation; I have notes here and on the AGMG discord, as well as see this wiki: https://github.com/bo3b/3Dmigoto/wiki

**Comment by KiyoshiMu** [comment]
Thanks a lot! https://github.com/bo3b/3Dmigoto/wiki is helpful
