### ISSUE TITLE
How to remove the shadows

### ISSUE THREAD

**Issue by SnownICE** [SilentNightSound/GI-Model-Importer#56]
Could you tell me in detail aboult #13 of Mona Hat Removal Walkthrough,I don't know how to remove the shadows.
老铁，莫娜帽子移除教程的第13条去除阴影是怎么做到的，能详细讲讲吗。
[https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Guides/MonaWalkthrough.md](url)

**Comment by SilentNightSound** [comment]
The shadows are controlled by the lightmap - what I did was look for the color that corresponds to the parts without shadow, copied it, then filled in the parts that have shadow with that color. For how to use paint.net, see tutorials like https://www.youtube.com/watch?v=NnTXMAZ2tBw

**Comment by SnownICE** [comment]
> The shadows are controlled by the lightmap - what I did was look for the color that corresponds to the parts without shadow, copied it, then filled in the parts that have shadow with that color. For how to use paint.net, see tutorials like https://www.youtube.com/watch?v=NnTXMAZ2tBw

oh,thank you so much,I think I get it the idea.
噢，我的上帝啊，感谢主的馈赠，我想我知道咋弄了。

**Comment by SilentNightSound** [comment]
Glad to hear!
