### ISSUE TITLE
Nilou Reflection Normal Map Bug

### ISSUE THREAD

**Issue by VelouriasMoon** [SilentNightSound/GI-Model-Importer#57]
Nilou's model uses a normal map unlike most other characters which seems to be under ps-t0 but that's also the texture used for the reflection colour map, setting the diffuse to ps-t0 fixes the reflection but then introduces lighting issues on the model itself.

![image_2023-01-13_043522711](https://user-images.githubusercontent.com/52844176/212274941-f4a98625-ba85-4f40-9527-0a7ff591faf8.png)

**Comment by Modder4869** [comment]
https://github.com/HummyR/GIMI-Tutorials/blob/main/Version_3_Character_Shader_Fix.md

**Comment by VelouriasMoon** [comment]
Thank you, that solves the issue.
