### ISSUE TITLE
(Not an issue)Write more information about how to re-apply the alpha channel in "MonaWalkthrough.md"

### ISSUE THREAD

**Issue by Awxgxny** [SilentNightSound/GI-Model-Importer#6]
I would really appreciate it, thank you!

**Comment by SilentNightSound** [comment]
No problem, will add it a little later. For now, refer to: https://github.com/zeroruka/GI_Assets/wiki/Creating-Skins for an explanation

**Comment by SilentNightSound** [comment]
Added more information about editing textures in the Mona walkthrough

**Comment by Awxgxny** [comment]
> Added more information about editing textures in the Mona walkthrough

Thank you so much! ❤️
