### ISSUE TITLE
GI 3.3 server mona capless not working

### ISSUE THREAD

**Issue by BFenKr** [SilentNightSound/GI-Model-Importer#61]
Hey, I have try "MonaBottomHeavyCapelessMod(CN)" in genshin impact 3.3 server and that not working but "MonaBottomHeavyMod" working. Any idea to fix it?

**Comment by SilentNightSound** [comment]
Double check which version the mod goes over, Mona has two outfits (and most modders use the CN outfit since that is the one that shows up in cutscenes)

**Comment by SilentNightSound** [comment]
No update in several weeks, closing ticket
