### ISSUE TITLE
d3d11.dll keeps changing

### ISSUE THREAD

**Issue by HimitsuYami** [SilentNightSound/GI-Model-Importer#64]
Whenever I launch 3DMigoto Loader.exe the d3d11.dll file keeps getting changed to d3d11.dll.2010359505 or some other random string of numbers and isn't recognized for a second launch. But if I change the ini file to the newly renamed d3d11.dll.2010359505 it isn't recognized as 3DMigoto anymore. The end result being that I have to manually rename the dll every time I want to launch the game.

**Comment by Modder4869** [comment]
dont put it in same folder as game , otherwise game will keep trying to rename it or delete

**Comment by SilentNightSound** [comment]
As Modd said, this is because the game renames the dll if it is in the same folder - put it in any other folder. Marking as resolved, closing.
