### ISSUE TITLE
Non folder mods not working

### ISSUE THREAD

**Issue by Snowflei** [SilentNightSound/GI-Model-Importer#65]
Only the mods in the folders are working for some reason and not the ones in files and i dont know what to do

**Comment by SilentNightSound** [comment]
Mods need to be extracted before being used - a "single file" mod is probably one that is a .zip/.rar/.7z

**Comment by Snowflei** [comment]
It worked, thank you for helping.

**Comment by alopiix** [comment]
It doesn't let me extract files, the option doesn't show up.
