### ISSUE TITLE
How to add "match_priority=n"  to suppress hash warning

### ISSUE THREAD

**Issue by AiasAuditore** [SilentNightSound/GI-Model-Importer#69]
About
 "WARNING: Possible Mod Conflict: Duplicate TextureOverride hash=
[TextureOverride\...]
[TextureOverride\...]
If this is intentional, add a match_priority=n to suppress warning and disambiguate order"

Where or how to add "match_priority=n"  to suppress this warning?

Thank you

**Comment by multyfora** [comment]
in the .ini file of mod, but if its showing it probably means you have 2 mods changing one object and it could look cursed, so better just find files that error says and delete one of them

**Comment by SilentNightSound** [comment]
As multyfora said, you can add it in the ini file but usually that message is an indication that multiple mods are modifying the same files - it is better to find the overlapping ini lines and delete one of them. Closing ticket
