### ISSUE TITLE
Can we replace face models?

### ISSUE THREAD

**Issue by mika32154** [SilentNightSound/GI-Model-Importer#7]

**Comment by SilentNightSound** [comment]
Not at the moment, I'm currently looking into it. It's unlikely you can edit face shapes since they are shared between characters, but it should be possible to modify textures since they are unique - I'm just not sure how yet

**Comment by SilentNightSound** [comment]
The current version now support replacing face textures - just grab the most up-to-date character files and scripts, then modify the face textures to change them
