### ISSUE TITLE
如何组合dump出来的模型？

### ISSUE THREAD

**Issue by 100SHIKI** [SilentNightSound/GI-Model-Importer#70]
I dumped  Shinobu's  "BodyHead" and "Mask " model with [genshin_3dmigoto_collect.py],  
I  try to combine  there folders  to  one folder ，but in game the Character mesh crush.
I would like to ask how to combine the various models of Shinubo, just like those in the GIMI-Assets-main library?

GIMI-Assets-main库里的Shinobu模型似乎有些问题，头部和身体的贴图不能修改。
我尝试用genshin_3dmigoto_collect.py分别提取出了“头部和身体（Body&head）” 、“面具（Mask）”  两个文件夹
（脸部的贴图我也想用-vs参数提取，不过提取出来的文件夹是空的。）
用他们分别生成MOD是有效的。
参考的视频教程是
https://www.youtube.com/watch?v=wx4x3ti7mpk&list=PLzZJJGRywUroAQP_yf2lz3bWA7X5RpSK2&index=1

但是我不清楚要如何将两个文件夹合并到一起，我尝试将两个文件夹里的文件放在一起，并且将hash.json里的内容组合在一起，再用blender导出MOD。但是在游戏中使用该MOD时，模型的mesh四分五裂并且占满了屏幕。我想请问如何将Shinubo的各个模型合并在一起，就像GIMI-Assets-main库里的一样？

**Comment by leotorrez** [comment]
you can only use one mod per character. To mix several you can use a merge script
