### ISSUE TITLE
not displayed

### ISSUE THREAD

**Issue by Warlord0204** [SilentNightSound/GI-Model-Importer#77]
Hello, sorry to bother you, but I have a problem. My file, which was successfully exported and implemented in the MOD file, is not displaying even after refreshing. I would appreciate the help of an expert. Best regards.

**Comment by SilentNightSound** [comment]
There are a large number of possible reasons why it might not work, including: outdated character dump (hashes changed), wrong outfit (characters have multiple outfits), program not loading, and a few others - try looking at the troubleshooting guide and following the basic mona hat tutorial, and if you have more questions you can ask on the agmg discord

**Comment by Warlord0204** [comment]
I'm sorry, where is the troubleshooting guide? :/

**Comment by SilentNightSound** [comment]
https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Guides/Troubleshooting.md and https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Guides/MonaWalkthrough.md for the mona walkthrough. The mona walkthrough goes through step by step to get a mod working

**Comment by Warlord0204** [comment]
thx
