### ISSUE TITLE
Jean skins on genshin not working

### ISSUE THREAD

**Issue by knives2222** [SilentNightSound/GI-Model-Importer#79]
hi all other toons work but all of the Jean ones do not load

example file location they are two layers down like the other ones
G:\game mods\genshin impact\3dmigoto-GIMI-for-playing-mods\3dmigoto\Mods\Jean Mod\JeanMod bath

none working Mod example skin https://gamebanana.com/mods/430266

working example other skins work file structure
G:\game mods\genshin impact\3dmigoto-GIMI-for-playing-mods\3dmigoto\Mods\Candace\CandaceCom bikini

Mod https://gamebanana.com/mods/416691

mod importer 
https://gamebanana.com/tools/10093

some have suggested changing outfit but i dont own her so can only view her in archive :(

thanks

**Comment by knives2222** [comment]
Many thanks the response and please message me when this script is avaiable

**Comment by SilentNightSound** [comment]
Hello. The script is now available at https://gamebanana.com/tools/12667

**Comment by Kempet1896** [comment]
Is this worked? I have the same problem... Like for EVERY Jean skin mods; none of them workd
