### ISSUE TITLE
mirroring issue

### ISSUE THREAD

**Issue by fgtqz** [SilentNightSound/GI-Model-Importer#8]
If i use a custom model the model is mirrored in game, if i mirror it in blender it goes all broken ingame, can i fix that?

**Comment by fgtqz** [comment]
i suspected that was a issue but also the texture on the model looks messed up 
![unknown](https://user-images.githubusercontent.com/108305765/176073679-b28f67f3-2dea-4434-be2a-e52dd024e942.png)

**Comment by fgtqz** [comment]
actually i found out this is a outline issue, im not sure how to fix it 
![unknown](https://user-images.githubusercontent.com/108305765/176077127-9dd000e1-30be-442f-a1fe-a843c845f622.png)

**Comment by SilentNightSound** [comment]
There are a few things that can cause that, but I can think of two main ones: either the original texture is in an incorrect format (e.g. not a .dds saved as BC7 SRGB with an alpha layer) or the COLOR component of the model has the line thickness set to the largest possible value (vertex color has RGBA, and I've seen a few models where the A component is set to 1.0 which seems to cause the entire model to become shadowed).

For the former, double check the textures you are using are similar in format to the ones from the CharacterData folder. 

For the latter, I'm not actually 100% sure how to edit vertex COLOR in blender or if it is possible. I'm planning to push out an update in the next day or two that adds the option to set the COLOR when exporting, but for now if you want to try playing with the values yourself you can try with the https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Tools/Edit3DMig_ver1.0.zip program I just uploaded. 

It has a readme.pdf and is covered in this video: https://youtu.be/z2nvJzkwHHQ?t=5211, and if you follow the instructions you can modify the COLOR values of the Head and Body .vb and regenerate the mod folder using the python genshin_3dmigoto_generate.py to see if that fixes the issue.

**Comment by fgtqz** [comment]
Tysm for your help the issue was with normals
![unknown](https://user-images.githubusercontent.com/108305765/176091461-c8a8b6a3-e6cd-44c8-9326-d15689e01f29.png)
