### ISSUE TITLE
Error when merging mods: ValueError - too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by zy32153** [SilentNightSound/GI-Model-Importer#81]
I'm having trouble merging these two mods:

-see https://gamebanana.com/mods/427108

I've successfully merged other mods before, but when trying to merge these two, I get the following error message:

-----error message-----
File "...genshin_merge_mods.py", line 271, in parse_section
    key, data = line.split("=")
ValueError: too many values to unpack (expected 2)
-----error message-----

**Comment by Modder4869** [comment]
some mods cant be merged but try v7 branch version of script

**Comment by SilentNightSound** [comment]
It's a known issue in the V6 script yeah. Try v7 (in a branch) to see if it works or fix the ini manually

**Comment by zy32153** [comment]
> some mods cant be merged but try v7 branch version of script

v7 branch works!! Thank you so much for your help!

**Comment by zy32153** [comment]
> It's a known issue in the V6 script yeah. Try v7 (in a branch) to see if it works or fix the ini manually

It works!! Thank you so much!

**Comment by SilentNightSound** [comment]
Glad to hear!
