### ISSUE TITLE
Not an issue exactly,I wonder is there a key which can unload all mods temporarily when playing games ?

### ISSUE THREAD

**Issue by Waitfyo** [SilentNightSound/GI-Model-Importer#92]
I know that F10 can reload all mods when playing games,buit is there a key which can unload all mods temporarily when playing games?

**Comment by HummyR** [comment]
f6 press to remove mods from view
f9 hold in dev mode to remove mods from view

**Comment by Waitfyo** [comment]
Thanks a lot, the version I used is too old, after updating to the newest version,I see the help menu and it works,haha.
