### ISSUE TITLE
missing d3dx.ini

### ISSUE THREAD

**Issue by Caotico-Metai** [SilentNightSound/GI-Model-Importer#94]
![image](https://user-images.githubusercontent.com/127855589/236950560-16fc11ed-5ee0-439b-a7fa-eb7751512c34.png)
i tried running the exe file but it shows this.
![image](https://user-images.githubusercontent.com/127855589/236950887-c32862e9-cdf9-41af-98b0-3c1294d0738f.png)
these are the files that i have

**Comment by HummyR** [comment]
Please come to the #verification-support channel in https://discord.gg/agmg if you need further help. For now, I suggest that you get the latest GIMI release and re-extract your GIMI zip file in case of corrupted data. If this does not work, try moving the GIMI folder to a different place as the current folder it is in may have restricted permissions.
